### ISSUE TITLE
Preview SVG icons at design-time

### ISSUE THREAD

**Issue by carloBarazzetta** [EtheaDev/SVGIconImageList#100]
At design-time, the component editor cannot show the svg icon preview into the OpenDialog when loading files from "Add..." button.
Compiling the demo, and and activating any VCLStyle, the icon is visibile:
![image](https://user-images.githubusercontent.com/7803548/92015795-98358680-ed51-11ea-8a70-edb7d14173e7.png)

Could it be possible to have the same functionality at design time?
We need some "hook" of the OpenDialog to inject the preview?

**Comment by carloBarazzetta** [comment]
@vincentparrett or @pyscripter : any idea to resolve this issue?

**Comment by pyscripter** [comment]
No idea I am afraid.  Why don't you post a question at delphi praxis?

**Comment by carloBarazzetta** [comment]
> No idea I am afraid. Why don't you post a question at delphi praxis?

Good idea!

**Comment by vincentparrett** [comment]
You would probably need to create and register your own component editor.

**Comment by carloBarazzetta** [comment]
Ok, I've resolved, with this solution:

I'm using a new class, implementing Execute without call the "inherited" metod, because the "magic" OpenDialog with the preview is activated by :  Template := 'DLGTEMPLATE' but it's used only when TStyleManager.IsCustomStyleActive

Using Template 'DLGTEMPLATE' also without CustomStyleActive shows always the dialog with the preview:
 
```
TOpenPictureDialogSvg = class(TOpenPictureDialog)

function TOpenPictureDialogSvg.Execute(ParentWnd: HWND): Boolean;
begin
  if (NewStyleControls and not (ofOldStyleDialog in Options) and
      not ((Win32MajorVersion >= 6) and UseLatestCommonDialogs)) or
     ((shDialogs in TStyleManager.SystemHooks)) then
    Template := 'DLGTEMPLATE'
  else
{$IF DEFINED(CLR)}
    Template := '';
{$ELSE}
    Template := nil;
{$ENDIF}
  Result := DoExecute(@GetOpenFileName, ParentWnd);
end;
```
Not very elegant, but it works...
