### ISSUE TITLE
Performances with VirtualImageList

### ISSUE THREAD

**Issue by carloBarazzetta** [EtheaDev/SVGIconImageList#109]
I've added a new unit UMainNew.pas/dfm used with 10.3 and 10.4 demo that contains a native VirtualImageList.
Now the VirtualImageList is always filled with all the icons contained in the collection and the performances resizing icons are very bad.
Clearing and adding a single Icon to the collection, when I resize the imagelist it fires four requests to TSVGIconImageCollection.GetBitmap -> calls SVGIconItem.GetBitmap, so it redraws the same Bitmap four times!!!
Our component SVGIconVirtualImageList fires SVGIconItem.GetBitmap only one time...
How we can resolve this problem?

**Comment by carloBarazzetta** [comment]
@pyscripter or @vincentparrett, are you using the native VirtualImageList? don't you have performance problems of this kind?

**Comment by vincentparrett** [comment]
I haven't gotten to that part yet. I'm busy converting all my images to svg and creating resources for the 100 packages that FinalBuilder loads, (loading the svg's from resources). 

I suspect this is similar to the issue with the demo, it's very slow when changing the image size. I haven't had time to look into where the perf issue is though.

**Comment by luebbe** [comment]
I'm also working towards this in our application. 
We are already using svg images. One thread loaded them (about 160 icons) upon startup of the application, converted them into bitmaps and stored them in six normale imagelists (three sizes * enabled/disabled). This took approximately four seconds for roundabout 1000 icons (160*6) which were created. After that the icons are cached as bitmaps and the svg conversion is only run, when icons are changed/added.
I'm a bit scared, that a DPI change will trigger this four second delay, but since I'm not there yet, I can't tell. I'll keep you updated.

**Comment by pyscripter** [comment]
There are a couple of issues here:
- Firstly, in TMainForm.FormAfterMonitorDpiChanged you are calling UpdateGUI.  This is unnecessary.  You do not need to 
handle AfterMonitorDpiChanged in the MainForm.  This doubles the number of painting calls.
- Secondly, after you fix the above, there are two calls made to the painting routines for each icon.   This is due to bad vcl design.  Either TCustomImageList.SetSize or TVirtualImageList.DPIChangedMessageHandler or both should call BeginUpdate/EndUpdate around the call to Scale.  Maybe this deserves an issue submission to Embarcadero.

In any case the delay in moving the Demo window with all 300 or so images between monitors is not that bad after you fix the first point.

@luebbe Please bear in mind that the virtual list should contain only the images of the containing form.   Typically each form only contains a few images and only those would be repainted.

**Comment by carloBarazzetta** [comment]
> * Firstly, in TMainForm.FormAfterMonitorDpiChanged you are calling UpdateGUI.  This is unnecessary.  You do not need to
>   handle AfterMonitorDpiChanged in the MainForm.  This doubles the number of painting calls.

Oh yes, it's an old piece of code!

**Comment by luebbe** [comment]
> @luebbe Please bear in mind that the virtual list should contain only the images of the containing form. Typically each form only contains a few images and only those would be repainted.

This may become difficult (or at least a "bit" of work). Right now we have an include file which contains the image indices as constants and is created by our iconset generator. During FormCreate e.g. the action "Close" receives the imageindex cImgClose, "FileOpen" receives cImgFileOpen and so on. We never have to touch this code when an image is added anywhere in the icon set and the index changes. 
Using only a subset would mean that in form A "Close" would have index 5 and in form B "Close" would have index 3.
I guess I could fill the forms virtual imagelist with a subset during create using the constants and assign the resulting index to the action. Let's see where this will lead :)

**Comment by pyscripter** [comment]
> Using only a subset would mean that in form A "Close" could have index 5 and in form B "Close" could have index 3.
> I guess I could fill the forms virtual imagelist with a subset during create using the constants and assign the resulting index to the action. Let's see where this will lead :)

Use imagenames and the PreserveItems property of VirtualImageList and you could forget about ImageIndex.

**Comment by carloBarazzetta** [comment]
> when I resize the imagelist it fires four requests to TSVGIconImageCollection.GetBitmap

Ok, I have optimized the Demo: now the calls are only Two, as you explained here " there are two calls made to the painting routines for each icon. This is due to bad vcl design."

**Comment by pyscripter** [comment]
> the application, converted them into bitmaps

Which library did you use for that?

**Comment by carloBarazzetta** [comment]
> Right now we have an include file which contains the image indices as constants and is created by our iconset generator.

Why do you need an IconSet generator? With SVGIconImageList you can obtain an icon an any size "on-the fly".
You can use the method:
function TSVGIconImageCollection.GetBitmap(AIndex: Integer; AWidth, AHeight: Integer): TBitmap;
or
procedure TSVGIconImageCollectionDraw(ACanvas: TCanvas; ARect: TRect; AIndex: Integer; AProportional: Boolean = False)

Before this calls you can call TSVGIconImageCollection.GetIndexByName(const AName: String): Integer; to obtain the icon index based on his name. If you are using categories, use the syntax GetIndexByName('Category/Name')

**Comment by luebbe** [comment]
> Which library did you use for that?

cairo

**Comment by luebbe** [comment]
> Why do you need an IconSet generator? With SVGIconImageList you can obtain an icon an any size "on-the fly".

The iconset "Generator" is a tool that I've written, which recursively collects svg files from a given directory, normalizes filenames, fixes some colours on the go and stores all svgs in a compressed filestream. Secondary output is a mapping table of icon name to index.
Right now the svgs are loaded by each application and the above mentioned six bitmap imagelists on a data module are filled on the fly. These imagelists are used everywhere.
Next step will be to replace the six bitmap imagelists by svg imagecollections. and have individual imagelists with only the needed icons on each form.
I plan to use the two methods that you mentioned above for the "singleton" icons/images that are not tied to actions.

**Comment by pyscripter** [comment]
> svgs are loaded by each application and the above mentioned six bitmap imagelists on a data module are filled on the fly

What do you use for that?

**Comment by luebbe** [comment]
> 
> 
> > svgs are loaded by each application and the above mentioned six bitmap imagelists on a data module are filled on the fly
> 
> What do you use for that?

the cairo bindings, originally by Henri Gourvest <hgourvest at progdigy dot com>. I can't remember where I got them from and can't find "my" version on SF or GH right now. There are cairo fpc bindings available here: https://github.com/DJMaster/cairo-fpc, which look like they are newer than the ones that I have.
I draw all Icons onto one large bitmap (ICairoContext on IWin32Surface) which is then sliced by the imagelist.

**Comment by pyscripter** [comment]
Cairo could be an additional SVG Factory.  Although at 4 seconds for 1000 svgs sounds rather slow.
@luebbe Does this include saving bitmaps to the file system?

**Comment by luebbe** [comment]
> Cairo could be an additional SVG Factory. Although at 4 seconds for 1000 svgs sounds rather slow.
> @luebbe Does this include saving bitmaps to the file system?

The four seconds are bad memory on my part. I just logged the timing at applicaton start:
- First call: 
  980ms load svg + modify colors on the fly + draw, 
  500ms save bitmap
- Second call: 
  880ms load svg + modify colors on the fly + draw, 
  470ms save bitmap

the 100ms load speed up in the second call can probably be attributed to the svg container being cached by windows this time.

Next application start:
- Loading the bitmap icons from file: 40-50ms. Hard to beat if you only want one image resolution.

**Comment by luebbe** [comment]
> 
> 
> > svgs are loaded by each application and the above mentioned six bitmap imagelists on a data module are filled on the fly
> 
> What do you use for that?

found it: https://github.com/kobi1970/delphignomevectorgraphic
It is indeed older than the other bindings are :D

**Comment by pyscripter** [comment]
Cairo sounds good.
@luebbe How much work it be to wrap it into an SVG Factory?  Have a look at SVGInterface.pas and the two implementation (D2D and Pas)?

**Comment by luebbe** [comment]
I can probably take a look next week.

**Comment by pyscripter** [comment]
Vcl issue reported as https://quality.embarcadero.com/browse/RSP-30931

**Comment by pyscripter** [comment]
Add the attached to your project to address the issue and reduce the time it takes to shift forms between monitors.
Requires DDetours (https://github.com/MahdiSafsafi/DDetours)

[FixRSP30931.zip](https://github.com/EtheaDev/SVGIconImageList/files/5215494/FixRSP30931.zip)

**Comment by vincentparrett** [comment]
Thx, I'll give it a try once I get all my svg images sorted, as I don't imagine Embarcadero will fix things anytime soon.
