### ISSUE TITLE
Incompatible with TImageList

### ISSUE THREAD

**Issue by vincentparrett** [EtheaDev/SVGIconImageList#11]
TSVGIconImageList has a compatibility issue with TImageList - the same one that TVirtualImageList does

https://quality.embarcadero.com/browse/RSP-28348

The simple fix is to change the base class to TDragImageList - that is the base class for TImageList.

**Comment by carloBarazzetta** [comment]
Hi Vincent, is an issue only for 10.4 ?

**Comment by vincentparrett** [comment]
No it would be a problem for all versions but I don't have anything earlier than XE7 installed at the moment to check with. 

FWIW, in 10.4 I took a copy of TVirtualImageList and changed the base class to TDragImageList - just that change - and that resolved the issue I had with TControl.GetDragImages.

**Comment by carloBarazzetta** [comment]
Resolved into 1.7 version.
