### ISSUE TITLE
Partly ugly antialiasing effects

### ISSUE THREAD

**Issue by luebbe** [EtheaDev/SVGIconImageList#111]
This is visible using the Demo when you switch to a dark design (e.g. Windows 10 Dark)

Fire up the editor and replace the businessman and businesswoman icons with the following svg:

```
<svg viewBox="0 0 33.00 33.00" xmlns="http://www.w3.org/2000/svg">
  <rect width="33" height="33" style="fill:#393A3F" rx="3" ry="3"/>
  <g transform="translate(3.50,3.50)">
    <path d="m13 0c-7.18 0-13 5.148-13 11.5 0 3.257 1.537 6.192 3.997 8.284-.678 2.864-4.099 4.046-3.874 4.856 2.165 1.247 7.991-1.128 9.883-1.959.963.201 1.962.319 2.994.319 7.18 0 13-5.148 13-11.5s-5.82-11.5-13-11.5zm1.927 17.415c-.488.202-1.628.725-2.673.725-.967 0-2.291-.446-2.291-1.875 0-1.656 1.173-4.015 1.173-5.383 0-1.523-1.98-.697-2.124-.642l.198-.814c.49-.2 1.649-.726 2.676-.726.833 0 2.249.3 2.249 1.875 0 1.581-1.171 4.112-1.171 5.382 0 .351-.045.907 1.049.907.426 0 1.01-.214 1.114-.262zm-1.387-10.218c-.708 0-1.784-.488-1.784-1.658 0-1.188 1.146-1.666 1.784-1.666.752 0 1.777.548 1.777 1.666 0 .677-.532 1.658-1.777 1.658z" fill="#CCC"/>
  </g>
</svg>
```
The important part is the rect with the rounded corners.

The preview on the left of the svg edit field shows the icon perfectly with crisp lines and no artifacts.
The listview on the top shows the icon with light pixels at the corners which look ugly on a dark background.

Small view (listview, not ok): 
![grafik](https://user-images.githubusercontent.com/3872576/93077440-17e41f00-f689-11ea-9ef0-526f6fba37eb.png)
Magnified view (listview, not ok): 
![grafik](https://user-images.githubusercontent.com/3872576/93077501-2b8f8580-f689-11ea-8033-57e05e17017a.png)
Magnified view (preview, perfect):
![grafik](https://user-images.githubusercontent.com/3872576/93077723-83c68780-f689-11ea-8822-8db11c7795d1.png)
Icon size 255 (listview not magnified):
![grafik](https://user-images.githubusercontent.com/3872576/93078112-34348b80-f68a-11ea-9100-25e2cfea3ca5.png)

The same effect is also visible in the demo's main form (toolbar, treeview and listview). 
Do you have an idea what is causing this effect? 
To me it looks like the antialiasing transistions to white instead of the background color.

**Comment by carloBarazzetta** [comment]
I'm not expert as @pyscripter but I suppose the problem was here: the components calls SVG.PaintTo passing a Bitmap initialized with:
PixelFormat := pf32bit;
Canvas.Brush.Color := $00FFFFFF; <=== probably this is the problem

The preview uses a TSVGIconImage component that draws the icon calling LSVG.PaintTo passing directly the Canvas already initialized.

I don't know how can we fix this problem.

**Comment by pyscripter** [comment]
> Canvas.Brush.Color := $00FFFFFF; <=== probably this is the problem

You could change 
$00FFFFFF; 
with 
StyleServices.GetSystemColor(clWindow)  // instead of clWindow you could you the system color with which toolbar buttons are drawn.

so that it blends better with the currently selected style (have not tried it).

**Comment by carloBarazzetta** [comment]
Using this code into function TSVGIconItem.GetBitmap appears good for me:

  if TStyleManager.IsCustomStyleActive then
    StyleServices.GetStyleColor(scGenericBackground)
  else
    Result.Canvas.Brush.Color := clWindow;

**Comment by carloBarazzetta** [comment]
This code into TSVGIconItem.GetBitmap works good for me:
```
  if TStyleManager.IsCustomStyleActive then
    Result.Canvas.Brush.Color := StyleServices.GetSystemColor(clWindow)
  else
    Result.Canvas.Brush.Color := clWindow;
  Result.SetSize(AWidth, AHeight);

```
but, in the demo, we must inform the image collection that the VCLStyle has changed calling:
ImageDataModule.SVGIconImageCollection.Change;

because VirtualImageList does not require a redraw of collection bitmaps when VCLStyle changes...

**Comment by luebbe** [comment]
Works for me too

**Comment by carloBarazzetta** [comment]
Resolved...

**Comment by pyscripter** [comment]
>    Result.Canvas.Brush.Color := clWindow;
I would use
>    Result.Canvas.Brush.Color := ColorToRGB(clWindow);

**Comment by pyscripter** [comment]
Unfortunately I cannot think of any way for the Image Collection to receive and handle style change notifications...  which would be desirable.

**Comment by carloBarazzetta** [comment]
> Result.Canvas.Brush.Color := ColorToRGB(clWindow);

Yes, It's correct... I've pasted your code without thinking...

**Comment by luebbe** [comment]
> 
> 
> Unfortunately I cannot think of any way for the Image Collection to receive and handle style change notifications... which would be desirable.

Why just the collection? Wouldn't also the imagelists need to be informed?

For me this worked out of the box without informing image(list|collection) about the style change, but I think this is because I have two sets of imagecollections (one for dark style and one for light), with pre-colored icons. When the style changes, I swap out the image collections underneath the imagelists.

**Comment by carloBarazzetta** [comment]
If you try the actual demo, removing line:
    ImageDataModule.SVGIconImageCollection.Change;
you can notice that after changing the VCL Style the method TSVGIconItem.GetBitmap is not called because VirtualImageList receive the message of type CM_CUSTOMSTYLECHANGED but don't forward to ImageCollection...

**Comment by luebbe** [comment]
Thanks for the Info. Wouldn't this be worth a report at QC?

**Comment by pyscripter** [comment]
This is not a bug.  TSVGImageCollection inherits from TComponent.  It is also typically located on a data module.   
Non-visual components don't normally need to receive notifications such as CM_STYLECHANGED.  
If it was a WinControl residing in a form then you would just implement a dynamic handler for CM_STYLECHANGED.  But here you can't.

One idea I had was about a TCustomImageList descendent that overrides DoDraw to draw directly the SVG, bypassing the need to create Bitmaps altogether.  However some components access the ImageList handle directly and use that for drawing by-passsing the Draw methods of ImageList and the would not work.

**Comment by luebbe** [comment]
> > Result.Canvas.Brush.Color := clWindow;
> > I would use
> > Result.Canvas.Brush.Color := ColorToRGB(clWindow);

Hi Folks,

I just tested the latest version and unfortunately the antialiasing effects are back again. The reason is that clWindow returns the window background color, which is not necessarily the color of the background on which the icons are drawn. e.g. clWindow may be white, but the toolbar is dark blue :)

I'd suggest to add a callback that allows the user to return the proper BG color for his design. If no callback is given, we can fall back to the current approach which will be ok in most cases.

I'll whip up a PR.

**Comment by pyscripter** [comment]
clWindow was a bad choice.  I would just use:

ColorToRGB(StyleServices.GetSystemColor(clBtnFace));

The above works whether Styles are enabled or not.  No need to have an if statement.   

But you will never get it perfect.  You may have the same VirtualImageList linked to a Toolbar, Buttons and VirtualTreeViews or other controls.   It cannot look perfect on all.

**Comment by luebbe** [comment]
You're right. This is why we already have different image collections. One for the toolbar icons (always kind of dark background) and one for the other icons. 
Since we have an inverse (dark) toolbar in the light design, clBtnFace looks about as bad as clWindow in this case.
A callback in the image collection would allow me give this image collection the right background color. This could then be passed into GetBitmap instead of determining the color there.

**Comment by carloBarazzetta** [comment]
We can use a property "AntialiasColor" on ImageCollection, by default clBtnFace, so you can define the color you need...

**Comment by luebbe** [comment]
That would solve the problem as well. Thanks for the pointers.
I was just digging through the classes in order to find the locations.

**Comment by carloBarazzetta** [comment]
> That would solve the problem as well. Thanks for the pointers.
> I was just digging through the classes in order to find the locations.

the property must be on TSVGIconItems class, the ImageCollection or the SVGIconImageList (the old component) must have only a Getter/Setter of this property...

**Comment by luebbe** [comment]
I thought so. You had me confused :grin:

**Comment by carloBarazzetta** [comment]
Added now AntialiasColor, check if it's good for you. By default uses clBtnFace.

**Comment by luebbe** [comment]
Thanks a lot. You beat me to it 😆.
I started to work on it yesterday afternoon and wanted to finish it today. I'll give it a try

**Comment by luebbe** [comment]
Perfect! Thanks a million!

![grafik](https://user-images.githubusercontent.com/3872576/93572344-fdb28580-f995-11ea-9fdb-5d80f1fe70d0.png)

**Comment by luebbe** [comment]
Hi Carlo,
my code looked almost identical to yours. The only differences I noticed were the following:

Your GetBitmap (everywhere)
```
function GetBitmap(const AWidth, AHeight: Integer;
      const AFixedColor: TColor; const AOpacity: Byte;
      const AGrayScale: Boolean; const AAntiAliasColor: TColor): TBitmap;
```
Mine (I combined the two TColor parameters):
```
function GetBitmap(const AWidth, AHeight: Integer;
      const AFixedColor, AAntiAliasColor: TColor;
      const AOpacity: Byte; const AGrayScale: Boolean): TBitmap;
```

I also saw that you have commented out `Change` in some of the Imagelist setters, but not everywhere. Is the `Change` unneccessary or are the comments left over from debugging?

**Comment by carloBarazzetta** [comment]
> function GetBitmap(const AWidth, AHeight: Integer;
>       const AFixedColor: TColor; const AOpacity: Byte;
>       const AGrayScale: Boolean; const AAntiAliasColor: TColor): TBitmap;

This is a "public" method, so I've added the new parameter to the end only for backward compatibility... but I've forgotten to define the new param with a default value (of clBtnFace)...

**Comment by carloBarazzetta** [comment]
> I also saw that you have commented out `Change` in some of the Imagelist setters, but not everywhere. Is the `Change` unneccessary or are the comments left over from debugging?

Yes, the calls to "Change" inside BeginUpdate and EndUpdate I suspect it's not necessary... but I've leaving the code "commented" because I'm not sure... and don't have time to make a test...

**Comment by pyscripter** [comment]
> the calls to "Change" inside BeginUpdate and EndUpdate I suspect it's not necessary...

It is necessary

**Comment by carloBarazzetta** [comment]
Ok. changed and fixed.
