### ISSUE TITLE
Cairo factory

### ISSUE THREAD

**Issue by luebbe** [EtheaDev/SVGIconImageList#112]
Since we started talking about adding cairo as another factory in #109, I took a look and I think I can add this factory during the next ~~two~~ few weeks. It's not a lot of work, but I need to do it in my spare time.

Two questions:
- Shall we move the factories and their units into a separate directory for each factory?
- What about the required header files and dlls for cairo? Shall we add them to the repo so that it works out of the box or shall we tell the user to "get it from there and copy it here"?

**Comment by carloBarazzetta** [comment]
Thank you for this contribution!
1) Now D2D Factory is contained into Source but TSvg factory is contained into \Source\Svg. You can do the same, using \Source\Cairo folder for your units.
2) I prefer to include all the include and dll files into this report with the appropriate license files.

**Comment by luebbe** [comment]
\Source and \Svg are not nested, but next to each other and the *Factory files are both in \Source.

**Comment by carloBarazzetta** [comment]
Sorry for my wrong explanation...
Into Source add the factory unit, then create a new Folder at the same level of Source for the implementation, same as Svg.
Project\Source\FactoryUnit
Project\Cairo\units... or Project\SVGCairo\units... if you prefer...
Then we must change {$DEFINE PreferNativeSvgSupport}...
Probably we can use:
{.$DEFINE SVGEngine}
{$DEFINE D2DEngine}
{.$DEFINE CairoEngine}
And activate only one of them... Do you agree @pyscripter ?

**Comment by pyscripter** [comment]
Yes sounds fine.

**Comment by luebbe** [comment]
I did roughly what you suggested in https://github.com/luebbe/SVGIconImageList/tree/cairo.
Please take a look.
So I'll move cairo out of the "source" folder and change the defines according to your suggestion.

**Comment by pyscripter** [comment]
> Please take a look.
CairoSVGFactory is not there yet?

And a questions.  Does one need to deploy all the DLLs in the DLL folder?

**Comment by luebbe** [comment]
> > Please take a look.
> > CairoSVGFactory is not there yet?

Yes, sorry. Just noticed this myself. I think the add got lost yesterday when I moved it between the cairo and source folder.

> And a questions. Does one need to deploy all the DLLs in the DLL folder?

Unfortunately yes. I tried to copy them one by one as the demo application complained about missing dlls and I couldn't leave out a single one.

We could leave them as a zip and unzip them during the build. We might also need to include the 64-bit dlls.

Recoloring is not yet implemented. Please take a look again :-)

**Comment by luebbe** [comment]
PS: Only the Delphi 10.4 demo has the paths etc. configured correctly to use cairo.

**Comment by pyscripter** [comment]
Have you done any comparison with the other factories.  How does it compare in fidelity, loading (parsing) speed, drawing speed?

> We might also need to include the 64-bit dlls.

Yes indeed.

**Comment by carloBarazzetta** [comment]
Today I've generated a new release (v.2.1.1) and have requested a resubmission to Get-It, so we can go ahead to include Cairo support without the risk of breaking anything...

**Comment by luebbe** [comment]
> 
> Have you done any comparison with the other factories. How does it compare in fidelity, loading (parsing) speed, drawing speed?

The output looks identical to me no matter which factory I use. I'd like to benchmark them, but haven't found time yet to think it through.

**Comment by carloBarazzetta** [comment]
An easy method to measure the speed of the library is to use the SVGExplorer that loads and draws all the icons present in a disk folder like the folder SVGIconImageList\Demo\Papirus-icons...

**Comment by luebbe** [comment]
So, I just added a simple benchmark to my cairo branch. Please take a look if you see any errors.
Currently it just loads and draws a SVG image N times and prints the ticks needed for each loop.

I didn't check for any double-buffering options, wich might improve performance especially for the pas SVG factory. Neither did I implement any recoloring benchmarks. I'll do this when I have implemented recoloring for the cairo factory.

The results seem to depend a lot on the complexity of the image. Any of the four SVG Examples sees a different engine in front.

Even though I use LoadFromStream in order to avoid file system influence, the first round of parsing (first engine, load N times) varies a lot and I don't understand why. Maybe overhead from loading the dlls?

Please take a look and give me some feedback.

**Comment by carloBarazzetta** [comment]
I'm testing your cairo branch, but changed some defines, because we have three engines but the native is available only with recent Delphi 10 versions, so I prefer this version:

```
//Prefer Engine Direct2D by Kiriakos Vlahos
//if supported by Windows Platform (from Windows Creators update)
{$DEFINE PreferNativeSvgSupport}
{.$DEFINE GPUSupport}

//if PreferNativeSvgSupport not active or not available:
//use Delphi Engine TSVG by Martin Walter (included into SVG folder)
{$DEFINE Delphi_SVGEngine}
//or use Engine Cairo wrapper (included by Lübbe Onken in Cairo folder)
{.$DEFINE Cairo_SVGEngine}

```
and one of Delphi_SVGEngine or Cairo_SVGEngine must be always defined.

For this reason into D2DSVGFactory I've made those changes:

```
{$IF DEFINED(Cairo_SVGEngine) and DEFINED(Delphi_SVGEngine)}
  {$MESSAGE FATAL 'You must define only one engine (Cairo_SVGEngine or Delphi_SVGEngine) into SVGIconImageList.inc)'}
{$ENDIF}
{$IF NOT DEFINED(Cairo_SVGEngine) and NOT DEFINED(Delphi_SVGEngine)}
  {$MESSAGE FATAL 'You must define at least Cairo_SVGEngine or Delphi_SVGEngine into SVGIconImageList.inc)'}
{$ENDIF}

{$IF DEFINED(Delphi_SVGEngine)}
  {$MESSAGE HINT 'Use Delphi (TSVG) SVG-Engine'}
  PasSVGFactory
{$ELSEIF DEFINED(Cairo_SVGEngine)}
  {$MESSAGE HINT 'Use Cairo SVG-Engine'}
  CairoSVGFactory
{$ENDIF}
{$IFDEF PreferNativeSvgSupport}
  {$MESSAGE HINT 'but Prefer Windows Direct-2D SVG-Engine if available'}
  , D2DSVGFactory
{$ENDIF}
  ;

```
and I've made some other changes... look at files attached.
[Source.zip](https://github.com/EtheaDev/SVGIconImageList/files/5257601/Source.zip)

If you want I'm ready to add your implementation of Cairo support into my repo, or do you prefer to make a pull-request?

**Comment by carloBarazzetta** [comment]
I've made a performance test using SVGExplorer with a significant number of icons

**Comment by luebbe** [comment]
> If you want I'm ready to add your implementation of Cairo support into my repo, or do you prefer to make a pull-request?

Thanks for your review. 

GrayScale, FixedColor and Opacity are not implemented in the Cairo branch (yet).

If that's ok, I'll add your changes and make a PR.

**Comment by carloBarazzetta** [comment]
Ok, no problem ... For now I am creating version 2.2 which contains the Cairo "wrapper". I am using this term to specify that it uses an external library: is this correct?

**Comment by luebbe** [comment]
Yes, I think that's the best way to word it

**Comment by carloBarazzetta** [comment]
@luebbe can you update Cairo support with latest Cairo version 2.5.2?

**Comment by luebbe** [comment]
@carloBarazzetta probably not. When I added Cairo support, I downloaded bindings and precompiled binaries for windows . I haven't found anything newer precompiled than librsvg 2.40 yet and I don't have a C Toolchain to build it myself. The Gnome sources are at 2.51 https://gitlab.gnome.org/GNOME/librsvg,
