### ISSUE TITLE
Markdownlint warnings

### ISSUE THREAD

**Issue by luebbe** [EtheaDev/SVGIconImageList#116]
The markdownlint plugin in VS-Code throws 68 warnings in Readme.md. Should I fix those?
Not important, just style. 😄

**Comment by carloBarazzetta** [comment]
Ok, make a pull request...

**Comment by luebbe** [comment]
No, just added the mention of Cairo as third factory.

I would fix the readme, but this would also mean that you have adapt your writing style in order to avoid future warnings ;)
If that's too much hassle, I'm not going to fix the lint warnings.
