### ISSUE TITLE
SVG opens as solid color - i.e. actual contents not visible.

### ISSUE THREAD

**Issue by LarsFosdal** [EtheaDev/SVGIconImageList#119]
The attached SVG opens with a single solid color in the SVG Image List demo.
Why is that? It does not look like that in the Windows 10 Power Pack previewer, nor in Inkscape.

[TINE Logo 2020.zip](https://github.com/EtheaDev/SVGIconImageList/files/5262128/TINE.Logo.2020.zip)

**Comment by LarsFosdal** [comment]
It seems to be the
`<g id="Guides">
	<rect class="st1" width="561.3" height="441.3"/>
</g>
`
section

**Comment by pyscripter** [comment]
This svg uses style sheets.   Windows Direct2D does not support styles in svgs.  This is [documented](https://github.com/EtheaDev/SVGIconImageList/wiki/Choice-of-Factories-(Direct-2D-or-GDI-)).

To use the Pascal TSVG disable the PreferNativeSvgSupport option in the include file.

**Comment by luebbe** [comment]
Could the D2D parser throw a warning when styles are used?

**Comment by pyscripter** [comment]
The parsing is done inside D2D.  You would have to then search for style elements (which would slow done everything).
In any case users will check their icons and pick a Factory that work for them during application development, not at run time.

**Comment by luebbe** [comment]
I know it's [documented](https://github.com/EtheaDev/SVGIconImageList/wiki/Choice-of-Factories-(Direct-2D-or-GDI-)), but should we add a one-liner to svgiconimagelist.inc or svginterfaces.pas? People (developers 😁) will probably look in the code and not in the docs.
I added one to svginterfaces for the need to copy the rsvg libs when using cairo.

**Comment by LarsFosdal** [comment]
It could be a warning in the dialog where you add images to a collection.  In theory, it could highlight the offending style(s).

**Comment by luebbe** [comment]
That would help at design time, but as Kiriakos said, you have to spend some extra time scanning for styles after parsing.
I'm filling the collections at runtime, so I have to make sure that the svgs don't use styles beforehand.

**Comment by LarsFosdal** [comment]
Perhaps it could be an optional setting to check for invalid SVG styles that is enabled in the debug build and disabled in the release build?

**Comment by luebbe** [comment]
That sounds doable. Would it be enough to recurse through the xml tree and throw an exception, when the first "class" attributes or "text" node is encountered?

**Comment by pyscripter** [comment]
> that is enabled in the debug build
I would rather have an option in the include file, which you activate.

**Comment by luebbe** [comment]
I'm still trying to understand how to recurse through a xml tree with XmlLite. I'll need this for recoloring in cairo as well. Could do this without further thought using msxml, but since XmlLite much faster...

**Comment by pyscripter** [comment]
> I'm still trying to understand how to recurse through a xml tree with XmlLite

You can't.  There is no internal xml tree. You have to reparse the whole svg text.  This is the price you pay for parsing speed.  
In TSVG you build a tree representation while you parse the XML, which is what you traverse.

**Comment by luebbe** [comment]
I understood that there is no svg tree in XmlLite. For recoloring or simple validation as requested here, a hierarchy is not needed.

For D2D validation it may be sufficient to throw a regex at the plain svg text without parsing.

Cairo doesn't provide any access to the SVG tree representation. So for recoloring I have to work on the source and recreate the Cairo svg object. This will probably make recoloring slower than in the other factories. One could however cache the grayscaled SVG object once it has been created and switch to it the next time grayscale is needed. One could even cache all recolored SGV objects in a TDictionary<TColor, TSVgObject>.

**Comment by pyscripter** [comment]
> One could however cache the grayscaled SVG object once it has been created and switch to it the next time grayscale is needed. One could even cache all recolored SGV objects in a TDictionary<TColor, TSVgObject>.

I would keep it simple.  Just keep the original and changed text representation.

**Comment by pyscripter** [comment]
> I was still thinking along the lines of recursing through the xml nodes.

That's what XMLLite parsing does.
