### ISSUE TITLE
GetIt - Paths to Svg and Source not automatically available to project

### ISSUE THREAD

**Issue by LarsFosdal** [EtheaDev/SVGIconImageList#121]
I was surprised that I had to explicitly include the paths to Svg and Source in my projects for the GetIt installation of SVGIconImageList.  That doesn't happen for f.x. EurekaLog and TMS - and we compile those sources there in our builds as well.

Ref. a comment in another issue about directories - I am slightly concerned that the source is split into even more directories, as it makes it cumbersome to maintain paths for projects.  What about using unit names for grouping instead?
F.x.
SVGIcon.Factory.Common;
SVGIcon.Factory.Cairo;
SVGIcon.Factory.D2D;

**Comment by luebbe** [comment]
I like your suggestion. Normally that would be my choice as well, so only one path has to be included. But the cairo headers for example are copied from another project. We would have to rename them everytime we pull in a new version and change the references inside the files as well, which is probably not going to happen very often.

The same would probably also apply to the Pas SVG factory.

If carlo likes the suggestion, we can go this way, but then we have to agree on a naming convention first.
The files inside the cairo folder could all receive a "Cairo." prefix.

**Comment by carloBarazzetta** [comment]
About GetIt, probably the other components adds the folder to global search path of Delphi. 
I will ask Embarcadero to do it for these components too, it is not something I can do ...

**Comment by carloBarazzetta** [comment]
Now, in the last version published to GetIt It's ok.
