### ISSUE TITLE
Cairo does not compile in Win64

### ISSUE THREAD

**Issue by pyscripter** [EtheaDev/SVGIconImageList#124]
Please replace all conditional defines from
{$IFDEF WIN32}
to
{$IFDEF MSWINDOWS}

By the way try the factories on this one.  Cairo is massively faster
[seaborn.zip](https://github.com/EtheaDev/SVGIconImageList/files/5301119/seaborn.zip)

**Comment by luebbe** [comment]
I'll take care of the defines, The headers are "old". Thank you.

**Comment by luebbe** [comment]
Oh boy, massively is a nice understatement.

Here are the results "benchmark" (64-bit) on "seaborn" with one repetition on my work PC:

```
Repeat 1 times
Factory    |  Load  |  Draw  |  Total
Pascal     |  47375 |  39687 |  87062
Direct 2D  |    938 |   1141 |   2079
Cairo      |    281 |    109 |    390
```

**Comment by pyscripter** [comment]
In drawing in particular Cairo is 11x faster than D2D and 400x faster than Pascal!

I wonder what is the reason for that.  Why don't we see similar results with smaller svgs...

**Comment by luebbe** [comment]
If you drop this SVG on Firefox it is also drawn a lot faster than D2D and Pascal, but not as fast as Cairo (not timed, just "feeling")

**Comment by pyscripter** [comment]
One encouraging thing is that at least all three factories produce the same visual output.

**Comment by carloBarazzetta** [comment]
Pull request merged.

**Comment by carloBarazzetta** [comment]
I can't wait to try Cairo with lots of "little icons" using SVGExplorer to measure performance again ;-)

**Comment by pyscripter** [comment]
@luebbe  Could you please check https://github.com/preshing/cairo-windows
This guy produces releases packaging all cairo functionality in a single dll:

> This repository is meant to help create Cairo DLLs for Windows. Both 32-bit and 64-bit versions can be built. The resulting cairo.dll file is fully self-contained and does not depend on any other third-party DLLs. FreeType support is included.

The releases include DLLs compiled last month.  It would a huge help to have to deploy one dll as opposed to 15.

**Comment by pyscripter** [comment]
With the changes in SVG.pas (see attached)

```
Repeat 1 times
Factory    |  Load  |  Draw  |  Gray  |  Draw  |  Fixed |  Draw  |  Total |
Pascal     |    312 |   2141 |    313 |   2140 |    625 |   2078 |   7609 |
Direct 2D  |    719 |    859 |    688 |    906 |    735 |    921 |   4828 |
Cairo      |    204 |    203 |    109 |    188 |    109 |    187 |   1000 |
```

However the painting comparison is fair for SVG.pas.  It draws directly on the SVGIconImage Canvas whilst the other two do buffered painting.  A fairer comparison would be to draw to a Bitimap.  In a production setting you would set DoubleBuffered on on the SVGIconImage and when it is painted with SVG the painting would be on a bitmap.

[SVG.zip](https://github.com/EtheaDev/SVGIconImageList/files/5308739/SVG.zip)

@carloBarazzetta Could you please commit the changes
@luebbe Could you please change the BenchmarkDraw to paint to a bitmap?

**Comment by pyscripter** [comment]
You want believe this.  With the above changes TSVG painting is super fast.  To try:
- Change the alignment on the UBenchmark form  Memo and splitter left aligned, SVGIconImage alClient so that the SVGImage size changes when you resize the form
- Make SVGIconImage Doublebuffered
- Define the TSVG as the default factory
- Run and load the seaborn.svg
- Resize the form quickly.

I 'd love to see the updated benchmarks on Bitmap.

**Comment by pyscripter** [comment]
One last thing.  There are a number of Warnings when I build UBenchmark (mostly on the Cairo side).  Could these warnings be eliminated?

**Comment by carloBarazzetta** [comment]
> @carloBarazzetta Could you please commit the changes

Done!

**Comment by luebbe** [comment]
> One last thing. There are a number of Warnings when I build UBenchmark (mostly on the Cairo side). Could these warnings be eliminated?

These are thrown, because I haven't found time yet to implement the recoloring using xmllite. So the getters don't return a value. I can make them return default values and add a Todo until this is done...

**Comment by pyscripter** [comment]
> Done, but changed
> FIdDict.TryAdd(Name, Result);

in TSVG.FindByID 
`
if not FIdDict.ContainsKey(Name) then

`This is not needed, since we checked above with TryGetValue

**Comment by carloBarazzetta** [comment]
Is this correct?
```
function TSVG.FindByID(const Name: string): TSVGObject;
begin
   if not FIdDict.TryGetValue(Name, Result) then
   begin
     Result := inherited FindById(Name);
     if Assigned(Result) then
       FIdDict.Add(Name, Result);
   end;
end;

```

**Comment by pyscripter** [comment]
```
function TSVG.FindByID(const Name: string): TSVGObject;
begin
   if not FIdDict.TryGetValue(Name, Result) then
   begin
     Result := inherited FindById(Name);
     FIdDict.Add(Name, Result);
   end;
end;
```

**Comment by luebbe** [comment]
> @luebbe Could you please change the BenchmarkDraw to paint to a bitmap?

@pyscripter Hi Kiriakos, I made some changes to the benchmark form and functionality, but don't quite understand how to do this? SvgIconImageCollection just has a Draw to Canvas method?!?

**Comment by pyscripter** [comment]
> > @luebbe Could you please change the BenchmarkDraw to paint to a bitmap?
> 
> @pyscripter Hi Kiriakos, I made some changes to the benchmark form and functionality, but don't quite understand how to do this? SvgIconImageCollection just has a Draw to Canvas method?!?

Create a bitmap of the right size and draw to the Bitmap.Canvas

**Comment by luebbe** [comment]
OK, but that means that the painting itself is not visible, if I understand you correctly?

**Comment by pyscripter** [comment]
> means that the painting itself is not visible, if I understand you correctly?
Yes.

**Comment by luebbe** [comment]
I made the drawing on TBitmap.Canvas an option in #128. Default is visible. OK this way?

Maybe we should turn all three options off by default, because cairo can't recolor yet and thus gains an undeserved advantage, since it does nothing.

**Comment by pyscripter** [comment]
TSVG is the fastest! Paints 3 times as fast as Cairo!

```
Benchmark: Repeat 10 times. Draw invisible.
Factory    |  Load  |  Draw  |  Total
Pascal     |   2312 |    329 |   2656
Direct 2D  |   6266 |   7734 |  14000
Cairo      |   1860 |    984 |   2844
```

**Comment by luebbe** [comment]
Thanks 🥰 ! The compliments go back to @pyscripter for your work on TSVG. This should improve resizing of Imagelists dramatically.

**Comment by carloBarazzetta** [comment]
I've pushed now a new version of Benchmark project, compatible also with XE6.

**Comment by luebbe** [comment]
Just saw it. Any reason why you removed the option to draw on an invisible Bitmap?

**Comment by luebbe** [comment]
Yeehaaaw!

Using the "Butterfly":

```
Benchmark: Repeat 50 times. Draw visible.
Factory    |  Load  |  Draw  |  Total
Pascal     |    250 |    250 |    500
Direct 2D  |    359 |    391 |    765
Cairo      |    110 |    297 |    407

Benchmark: Repeat 50 times. Draw invisible.
Factory    |  Load  |  Draw  |  Total
Pascal     |    250 |     16 |    266
Direct 2D  |    265 |    360 |    625
Cairo      |    125 |     62 |    187
```

We should update our Benchmark in the Readme 😎

**Comment by luebbe** [comment]
I repeated the "invisible" draw several times. Pascal and Cairo times are pretty much consistent, but D2D can sometimes be unlucky.

```
Benchmark: Repeat 50 times. Draw invisible.
Factory    |  Load  |  Draw  |  Total
Pascal     |    250 |     16 |    266
Direct 2D  |    265 |    360 |    625
Cairo      |    125 |     62 |    187

Benchmark: Repeat 50 times. Draw invisible.
Factory    |  Load  |  Draw  |  Total
Pascal     |    235 |     15 |    250
Direct 2D  |    110 |    140 |    250
Cairo      |     94 |     62 |    156

Benchmark: Repeat 50 times. Draw invisible.
Factory    |  Load  |  Draw  |  Total
Pascal     |    235 |     15 |    250
Direct 2D  |    125 |    219 |    344
Cairo      |    109 |     63 |    172

Benchmark: Repeat 50 times. Draw invisible.
Factory    |  Load  |  Draw  |  Total
Pascal     |    235 |     15 |    250
Direct 2D  |    125 |     94 |    219
Cairo      |    125 |     62 |    187

Benchmark: Repeat 50 times. Draw invisible.
Factory    |  Load  |  Draw  |  Total
Pascal     |    235 |     15 |    250
Direct 2D  |    125 |    125 |    266
Cairo      |    125 |     47 |    187

Benchmark: Repeat 50 times. Draw invisible.
Factory    |  Load  |  Draw  |  Total
Pascal     |    234 |     16 |    250
Direct 2D  |    125 |     93 |    218
Cairo      |    125 |     47 |    172

Benchmark: Repeat 50 times. Draw invisible.
Factory    |  Load  |  Draw  |  Total
Pascal     |    235 |     15 |    250
Direct 2D  |    109 |     94 |    203
Cairo      |    110 |     62 |    172

```

**Comment by pyscripter** [comment]
One thing is sure.  TSVG vastly outperfomrs the others in Drawing speed.  And you typically load once but paint many times.
