### ISSUE TITLE
Better fix for #14

### ISSUE THREAD

**Issue by pyscripter** [EtheaDev/SVGIconImageList#129]
@carloBarazzetta If you remember your fix to #14 was to reduce the image size (the -1 in the code below).

``` pascal
  // The -1 below is for fixing #14. There may well be a better way.
  if (FViewBox.Width > 0) and (FRootBounds.Width > 0) then
    ScaleX := (FRootBounds.Width - 1) / FViewBox.Width
  else
    ScaleX := 1;
  if (FViewBox.Height > 0) and (FRootBounds.Height > 0) then
    ScaleY := (FRootBounds.Height - 1)/ FViewBox.Height
  else
    ScaleY := 1;
```
I was not very happy with this fix because you lose 1px of width and height and there was no reasonable justification for doing so.

I did some search and I found the following:
- https://stackoverflow.com/questions/20776605/missing-half-of-first-pixel-column-after-a-graphics-transform-scale/20776743
- https://photosauce.net/blog/post/image-scaling-with-gdi-part-3-drawimage-and-the-settings-that-affect-it
- https://docs.microsoft.com/en-us/windows/win32/api/gdiplusenums/ne-gdiplusenums-pixeloffsetmode

So my recommendation is to remove the above fix (the -1)

and replace all instances (a quick search showed 8 of those in the project) of

`Graphics.SetSmoothingMode(SmoothingModeAntiAlias);`
with
```
    Graphics.SetSmoothingMode(SmoothingModeAntiAlias);
    Graphics.SetPixelOffsetMode(PixelOffsetModeHalf);
```
I have done a bit of testing and it appears to work, but I would appreciate it if you check it yourself and apply the changes if you are happy with the outcome.

**Comment by carloBarazzetta** [comment]
In Italy that change is called "a hammer"! For sure what you propose is better than my solution!

**Comment by luebbe** [comment]
Interesting! In German we also say something is "der Hammer", if it's outstanding in one way or the other.

**Comment by carloBarazzetta** [comment]
Done now.
