### ISSUE TITLE
If this lib supports OpenGL factory, will FMX support macOS, linux, android, IOS? 

### ISSUE THREAD

**Issue by GaNacereddine** [EtheaDev/SVGIconImageList#130]
since you made it possible to use other engines, will the support of OpenGL make it possible to target MacOS, linux, android and IOS.

also since embarcadero will support metal, will it be reasonable to write wrappers for that as an engine on MacOS and IOS?

**Comment by pyscripter** [comment]
Cairo is also available on most platforms.

**Comment by carloBarazzetta** [comment]
@GaNacereddine: there is a new version of components (2.3.0) that uses a new engine Image32 that is compatible also with Android and iOS. I've not tested yet with Android and iOS, is not my primary business platform, but the FMX version of SVGIconsImageList now uses this new library that can be used also on Android and don't need windows units:
http://www.angusj.com/delphi/image32/Docs/Examples.htm
Please give me a feedback if you can try.

**Comment by carloBarazzetta** [comment]
In those days I've committed a new version for FMX...

**Comment by carloBarazzetta** [comment]
New version with demo for Android:
![image](https://user-images.githubusercontent.com/7803548/126030073-35782bf9-2725-458e-926a-80129941062c.png)

**Comment by carloBarazzetta** [comment]
No positive/negative feedback. I'm closing this issue.
