### ISSUE TITLE
SVGIconImage fixedColor inherited

### ISSUE THREAD

**Issue by amancini** [EtheaDev/SVGIconImageList#132]
Hello ,

after change for add FixedColor to TSvgIconImage , by default you set clDefault that not apply custom color to SVG.

Is my opinion, by default use inherit  color from the imagelist assigned to the TSVGIconIMage

i have edit SVGIconImage.pas

add new function 

```
function TSVGIconImage.GetInheritedFixedColor: TColor;
begin
  Result := SVG_INHERIT_COLOR;
  if not Assigned(FImageList) then Exit;

  if FImageList is TSVGIconImageListBase then
    Result := TSVGIconImageListBase(FImageList).FixedColor;
end;

```

on paint event

```
    if FFixedColor <> SVG_INHERIT_COLOR then
      LSVG.FixedColor := FFixedColor
    else
      LSVG.FixedColor := GetInheritedFixedColor;

```
best regards

**Comment by carloBarazzetta** [comment]
Fixed in 2.2.1 version.
