### ISSUE TITLE
Further optimization of the path element

### ISSUE THREAD

**Issue by pyscripter** [EtheaDev/SVGIconImageList#135]
See attached.
[SVG.zip](https://github.com/EtheaDev/SVGIconImageList/files/5324759/SVG.zip)

By the way a limitation of GDI+ and TSVG is that it does not support sub-pixel Pens  (i.e stroke-width < 1 is the same as stroke-width = 1)

**Comment by carloBarazzetta** [comment]
pushed.

**Comment by pyscripter** [comment]
Could you please remove the unused var P  in TSVGPath.ReadInAttr   (see @luebbe' s comment)

**Comment by carloBarazzetta** [comment]
Done.
