### ISSUE TITLE
TSVGIconImage change class from TCustomControl to TGraphicControl for repeat paint issue

### ISSUE THREAD

**Issue by amancini** [EtheaDev/SVGIconImageList#136]
Hello,

The TSVTIconImage is painted many times because during the drawing massage it is called the
procedures TWinControl.PaintHandler  (var Message: TWMPaint); that call the  PaintWindow (DC)

Why use TCustomControl and not use the "Classic" TGraphicControl  ?

By changing the class from which TCustomControl derives to TGraphicControl the problem is solved,
( the properties of doublebuffer and parentbuffered and paretBackground are lost )

I have attached a video with the effect produced and the fix on the SVGIconImage.pas

[5Q0gX3UtSI.zip](https://github.com/EtheaDev/SVGIconImageList/files/5326862/5Q0gX3UtSI.zip)
[SVGIconImage.zip](https://github.com/EtheaDev/SVGIconImageList/files/5326766/SVGIconImage.zip)

best regards

**Comment by carloBarazzetta** [comment]
Originally the component inherits from TGraphicControl, but we changed from TGraphicControl to TCustomControl to implement doublebuffered, as explained in this discussion:
https://github.com/EtheaDev/SVGIconImageList/issues/74

In your tests, are you using DoubleBuffered as True?

**Comment by amancini** [comment]
I try to set DoubleBuffered as true . but the repait issue was not resolved

**Comment by carloBarazzetta** [comment]
I'm thinking to revert the base class of TSVGIconImage from TCustomControl to TGraphicControl, because the DoubleBuffer option is provided automatically into Direct2D, Cairo and Image32 libraries.
Do you agree @pyscripter or am I wrong?

**Comment by pyscripter** [comment]
I think Direct2D, Cairo and Image32 paint to a bitmap and then render the bitmap to the DC.  TSvg draws directly to the DC.  I am not using TSvgIconImage and don't have strong views on this.

**Comment by carloBarazzetta** [comment]
Now I've committed a new version of TSVGIconImage:
* Changed parent class of TSVGIconImage from TCustomControl to TGraphicControl
- Those properties was eliminated:
ParentDoubleBuffered
DoubleBuffered
ParentBackground
Scale
(if an old dfm contains them, they are loaded and discarded).
- Some properties of TGraphicControls are now exposed:
    property Align;
    property Anchors;
    property Constraints;
    property DragCursor;
    property DragKind;
    property DragMode;
    property Enabled;
    property ParentShowHint;
    property PopupMenu;
    property ShowHint;
    property Touch;
    property Visible;
    property OnClick;
    property OnContextPopup;
    property OnDblClick;
    property OnDragDrop;
    property OnDragOver;
    property OnEndDock;
    property OnEndDrag;
    property OnGesture;
    property OnMouseActivate;
    property OnMouseDown;
    property OnMouseEnter;
    property OnMouseLeave;
    property OnMouseMove;
    property OnMouseUp;
    property OnStartDock;
    property OnStartDrag;

@amancini: can you make some test with the new version using also the new Image32 factory?

**Comment by carloBarazzetta** [comment]
No positive/negative feedback... I'm closing this issue.
