### ISSUE TITLE
Minor optimization

### ISSUE THREAD

**Issue by mWaltari** [EtheaDev/SVGIconImageList#139]
in SVGParse.pas

function ParseFontStyle(AFontStyle: string): Integer; 

Could be 

function ParseFontStyle(const AFontStyle: string): Integer;

**Comment by luebbe** [comment]
Looks like you ran FixInsight over the sources. Thank you :)

**Comment by mWaltari** [comment]
yes In did, we are starting to use SVGIconImageList, so I also ran the FixInsight on it.

**Comment by carloBarazzetta** [comment]
Fixed in 2.2.1 version
