### ISSUE TITLE
Scaling Problem

### ISSUE THREAD

**Issue by rittjom** [EtheaDev/SVGIconImageList#14]
Hi,

there might be a scaling Problem with specific SVG's.
In my example theres some pixels missing at the bottom of the SVG.
Inside the button theres also 1px of cropping on the right side.
I attached a screenshot and the SVG file i used to reproduce this behavior.
I'm using Delphi 10.4 Sydney 32bit Windows VCL Application without HighRes Support.

![ImageSvgScaling](https://user-images.githubusercontent.com/13555220/88289139-120b3680-ccf5-11ea-8733-2387f31af351.png)

[phone.svg.zip](https://github.com/EtheaDev/SVGIconImageList/files/4965994/phone.svg.zip)

**Comment by rittjom** [comment]
Oh now I see, you got the same Issue in the example Image of this library.

![ScalingProblem2](https://user-images.githubusercontent.com/13555220/88290480-22bcac00-ccf7-11ea-8a6a-e81b2cb64e8f.png)

**Comment by carloBarazzetta** [comment]
Please give me a feed-back if this changes resolve this problem:
procedure TSVG.PaintTo(Graphics: TGPGraphics; Bounds: TGPRectF;
  Rects: PRectArray; RectCount: Integer);
var
  M: TGPMatrix;
  MA: Winapi.GDIPOBJ.TMatrixArray;
begin
  Bounds.Width := Bounds.Width -1; <====== add this line
  Bounds.Height := Bounds.Height -1; <====== add this line

**Comment by rittjom** [comment]
Yes, that resolve this problem!

**Comment by carloBarazzetta** [comment]
Resolved into 1.7 version.
