### ISSUE TITLE
Difficult to work next weeks

### ISSUE THREAD

**Issue by carloBarazzetta** [EtheaDev/SVGIconImageList#142]
Hi all, 
On Sunday, I dislocated my shoulder and I am having difficulty working ...
Forgive me if I cannot give support. If you can do the pull-requests
![image](https://user-images.githubusercontent.com/7803548/98112344-584e6500-1ea2-11eb-8578-8550c7a25e4e.png)

**Comment by luebbe** [comment]
Ouch, get well soon!

**Comment by mWaltari** [comment]
Get well soon

**Comment by pyscripter** [comment]
At least it is not coronavirus.  Get well soon.
