### ISSUE TITLE
update the performance comparison

### ISSUE THREAD

**Issue by luebbe** [EtheaDev/SVGIconImageList#146]
Hi @carloBarazzetta, a while ago you made a performance comparison of the three engines on your PC. Since @pyscripter has improved the TSVG Engine a lot, it could be worthwile to repeat the test run on your PC. If you do this, I'll gladly update the README with the latest numbers.

**Comment by carloBarazzetta** [comment]
Done.

**Comment by pyscripter** [comment]
`But for handling large and complex SVG files such as the cowboy.svg in the Demo\svg_examples directory (367 KBs), Direct2D or Cairo has a clear edge. Direct2D can optionally use GPU support (see below), which might help when you deal with large SVG files.`

Not true any more.

**Comment by carloBarazzetta** [comment]
Ok! Fixed.
