### ISSUE TITLE
Support Windows 64-bit platform

### ISSUE THREAD

**Issue by szwajcar** [EtheaDev/SVGIconImageList#147]
Components do not support 64-bit Windows platform. Any reason?

**Comment by carloBarazzetta** [comment]
The VCL demo compiles and works perfectly even on a 64-bit platform. Have you encountered any specific problems?

**Comment by szwajcar** [comment]
Standard instalation via Get-It and standard Package have got only 32-bit platform. 

![Adnotacja 2020-11-28 134723](https://user-images.githubusercontent.com/24227245/100516056-4306e680-3181-11eb-9392-661ab67495cf.png)

Edited the package project and added the 64-bit Windows platform. It's already ok.

![obraz](https://user-images.githubusercontent.com/24227245/100516059-4ac68b00-3181-11eb-9beb-2f40e7bd61da.png)
