### ISSUE TITLE
Some SVGs drawn black

### ISSUE THREAD

**Issue by rittjom** [EtheaDev/SVGIconImageList#148]
Some of my SVGs get rendered complety black instead of the regular colors.

In the Attached file you can see the difference between TSvgIconImage in a VCL Windows Form and Edge Browser.
![svg_issue](https://user-images.githubusercontent.com/13555220/100778422-4ad7bc80-3407-11eb-8ac7-9d997548f2b8.png)

Here's the SVG Text:
`<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="48pt" height="48pt" viewBox="0 0 48 48" version="1.1">
<g id="surface20604269">
<path style=" stroke:none;fill-rule:nonzero;fill:rgb(94.509804%,76.862746%,5.882353%);fill-opacity:1;" d="M 39 15 C 39 12.800781 37.199219 11 35 11 L 29 11 C 28.300781 11 27.898438 10.199219 28.300781 9.601562 C 28.898438 8.601562 29.199219 7.398438 28.898438 6.101562 C 28.5 4.101562 27 2.5 25.101562 2.101562 C 21.800781 1.398438 19 3.898438 19 7 C 19 8 19.300781 8.800781 19.699219 9.601562 C 20.101562 10.199219 19.699219 11 18.898438 11 L 12.898438 11 C 10.699219 11 8.898438 12.800781 8.898438 15 L 8.898438 22 C 8.898438 22.699219 9.699219 23.101562 10.300781 22.699219 C 11.300781 22.101562 12.5 21.800781 13.800781 22.101562 C 15.800781 22.5 17.398438 24 17.800781 25.898438 C 18.5 29.101562 16 32 12.898438 32 C 11.898438 32 11.101562 31.699219 10.300781 31.300781 C 9.800781 30.898438 9 31.300781 9 32 L 9 38 C 9 40.199219 10.800781 42 13 42 L 35 42 C 37.199219 42 39 40.199219 39 38 Z M 39 15 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:rgb(26.274511%,62.7451%,27.843139%);fill-opacity:1;" d="M 46.535156 37.277344 C 46.535156 42.777344 42.035156 47.277344 36.535156 47.277344 C 31.035156 47.277344 26.535156 42.777344 26.535156 37.277344 C 26.535156 31.777344 31.035156 27.277344 36.535156 27.277344 C 42.035156 27.277344 46.535156 31.777344 46.535156 37.277344 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:rgb(100%,100%,100%);fill-opacity:1;" d="M 42.535156 35.277344 L 38.535156 35.277344 L 38.535156 31.277344 L 34.535156 31.277344 L 34.535156 35.277344 L 30.535156 35.277344 L 30.535156 39.277344 L 34.535156 39.277344 L 34.535156 43.277344 L 38.535156 43.277344 L 38.535156 39.277344 L 42.535156 39.277344 Z M 42.535156 35.277344 "/>
</g>
</svg>`

**Comment by carloBarazzetta** [comment]
Yes, I noticed it's a problem using the native TSVG engine instead of the Direct2D engine, and the reason is that fill:rgb with percentage values ​​doesn't work: if you try to change the RGB values ​​to an integer (0 to 255) instead of percentage it works well with the native TSVG engine.
I will investigate svg parser to implement rgb with percentage value... or you can try yourself if you want... ;-)

**Comment by carloBarazzetta** [comment]
Fixed now!

**Comment by rittjom** [comment]
Wow, what a quick fix. Thank you very much :) 👍
