### ISSUE TITLE
Problems ti install with RAD Studio 10.2 Tokio

### ISSUE THREAD

**Issue by quini27** [EtheaDev/SVGIconImageList#149]
Dear Carlo: I work with Delphi in RAD Studio 10.2 Tokio and with Python 3.8 installed with Anaconda 3 for windows 10, 64 bits. I am using the components Python4Delphi, and the VCL applications must be compiled for Windows 64 bits (because the version of the Python.dll). However, the SVGIconImageList design time component only can be installed with the target platform Win32. With win64 there is no option to install the components. The FMX components do not work with this version of RAD Studio, and there is no dpk package for FMX components in the SVGIconImageList-master\Packages\D10_2 directory. Any suggestion about how can I use the SVGIconImageList components in my Python4Delphi applications? Thank you in advance

**Comment by carloBarazzetta** [comment]
I've pushed 2.2.1 version: now all run-time packages can be compiled with 64bit platforms. Only design-time packages remains for win32 platform (IDE).
