### ISSUE TITLE
Create virtual SVG ImageList and SVG ImageCollection

### ISSUE THREAD

**Issue by vincentparrett** [EtheaDev/SVGIconImageList#15]
I really need this feature to be able to use this library, so I made a start on it. This will allow the handling of DPI changes on different forms that share the same list of images (as is common). Obviously the highdpi stuff is only in 10.3+ but it would still be useful, as we could do things like have multiple image lists, with different sizes using the same collection of svg's. 

I'm mostly coding this in XE7 as that's the earliest I have installed, but of course when I get to it I'll test with 10.3 and 10.4 - I have a 2 monitor setup with different dpi's so easy to test. 

I will open a draft pull request soon with the code for this.

So far I have done the following :

- Extracted TSVGIconItem and TSVGIconItems to a separate unit.
- Created a TSVGIconImageCollection class which will contain the TSVGIconItems
- Created a TSVGIconVirtualImageList class which uses the TSVGIconImageCollection for the list of images, and does the drawing etc.

For the moment I'm just copying and pasting parts of TSVGIconImageList as needed, but I can see a lot of duplication, so might look to introduce a new base class for both TSVGIconImageList and TSVGIconVirtualImageList as there is a lot of code duplication - I'll do that once I have confirmed my code is going to work.

**Comment by carloBarazzetta** [comment]
The pull request was merged!
Thank you very much.

**Comment by vincentparrett** [comment]
Thanks, about to start integrating it into FinalBuilder - only have a few thousand images to replace!
