### ISSUE TITLE
TSVGIconImage OnMouseDown event-handler is never called at run-time!

### ISSUE THREAD

**Issue by PeterPanino** [EtheaDev/SVGIconImageList#158]
In a Delphi 10.4.2 32-bit VCL Application, I use the component TSVGIconImage from the SVGIconImageList library from the GetIt PackageManager.
Although the component supports the OnDblClick event-handler at run-time, it does NOT support the **OnMouseDown** event-handler! I.e., I can add an OnMouseDown event-handler in my project by double-clicking the OnMouseDown event in the Object Inspector, however, that event-handler gets never called at run-time!

**Comment by carloBarazzetta** [comment]
Please download the latest version of the components from this repo: in the Demo SVGIconImageListDemo the event OnMouseDown is used and it works.
The version on GetIt will be updated soon.
