### ISSUE TITLE
Still rendering errors in ver.2.2.5

### ISSUE THREAD

**Issue by PeterPanino** [EtheaDev/SVGIconImageList#159]
When rendering this [SVG](https://svgshare.com/i/Upj.svg) in TSVGIconImage, there are still rendering errors: See this [screenshot](https://i.imgur.com/udgkTqU.png).

**Comment by PeterPanino** [comment]
Here is the SVG file (if the above link does not work):
[reactor.zip](https://github.com/EtheaDev/SVGIconImageList/files/6128363/reactor.zip)

**Comment by pyscripter** [comment]
The Pascal renderer may have issues with text elements.  The D2D does not support text.  So try the Cairo renderer and it should work.

Alternatively convert the text to path using Inkscape or some other svg editor.
