### ISSUE TITLE
Vcl.BaseImageCollection is automatically included in FMX applications

### ISSUE THREAD

**Issue by dkounal** [EtheaDev/SVGIconImageList#167]
I noticed that when saving an FMX application with a TSVGIconImageCollection the unit Vcl.BaseImageCollection is automatically included in the uses clause. 
Does TSVGIconImageCollection work with FMX?

**Comment by carloBarazzetta** [comment]
No, for FMX you must use only the TSVGIconImageList component like in SVGIconImageListDemoFMX (in demo folder).
The structure of an FMX ImageList in different from the vcl that uses an ImageCollection and a VirtualImageList: look at properties Source and Destination as explained here:
https://github.com/EtheaDev/SVGIconImageList/wiki/Component-Editor-(FMX)

**Comment by dkounal** [comment]
Thank you very much. It is OK now
