### ISSUE TITLE
different painting between different platforms and controls

### ISSUE THREAD

**Issue by dkounal** [EtheaDev/SVGIconImageList#168]
The attached svg icons have different representation between vcl TSVGIconImageCollection and fmx TSVGIconImageList
[Arrows.zip](https://github.com/EtheaDev/SVGIconImageList/files/6226538/Arrows.zip)

**Comment by carloBarazzetta** [comment]
It seems a problem related to the zoom factor: in fact if you set the zoom to 97% you can see both correctly.
I have to investigate to understand why.

**Comment by carloBarazzetta** [comment]
Please check the new 2.3.0 version with a complete replace of FMX engine by using Image32.

**Comment by carloBarazzetta** [comment]
Sorry but I've not yet committed an important file to use the new 2.3.0 lib with FMX.
Try now.
