### ISSUE TITLE
Drag&Drop planned ?

### ISSUE THREAD

**Issue by Serge-Girard** [EtheaDev/SVGIconImageList#170]
I was playing with some Easter eggs  (1 from 5, and random colors)
![image](https://user-images.githubusercontent.com/51124639/113584864-b76bfd80-962b-11eb-8640-323a5724c223.png)
till I found there is no drag&drop capabilities for SVGIconImage 
Did you plan to had it ?

**Comment by carloBarazzetta** [comment]
Maybe in the near future...

**Comment by carloBarazzetta** [comment]
The last version of TSVGIconImage was changed, reverted from TCustomControl to TGraphicControl, and the properties of TGrahicControl are fully exposed as a standard TImage.
