### ISSUE TITLE
Text not rendered properly

### ISSUE THREAD

**Issue by rittjom** [EtheaDev/SVGIconImageList#175]
Hi,

in my example SVG the Text Rendering seems to be incorrect.

Expected:
![badge_correct](https://user-images.githubusercontent.com/13555220/115382327-d72b2600-a1d4-11eb-8c50-61ab52cf90fe.png)

Actual:
![badge_wrong](https://user-images.githubusercontent.com/13555220/115382350-dc887080-a1d4-11eb-966d-7f1e44e49c38.png)

Example SVG:

[badge_bug_text_anchor_middle.svg.zip](https://github.com/EtheaDev/SVGIconImageList/files/6342787/badge_bug_text_anchor_middle.svg.zip)

**Comment by carloBarazzetta** [comment]
You are using some keywords not "managed" by this library.
You can correct the text like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="48px" height="48px">
<g id="badge_right_top">
<rect fill="#f23a3a" id="badge_right_top_rect" width="24" height="14" x="1" y="2" rx="4" ry="4" />
<text fill="#ffffff" id="badge_right_top_text" font-family="Arial, sans-serif;" font-size="12" font-weight="bold" x="3" y="13">999</text>
</g>
</svg>
```

If you want, you can use this useful viewer/editor to edit manually your SVG files:
https://github.com/EtheaDev/SVGShellExtensions
