### ISSUE TITLE
Text are not drawed

### ISSUE THREAD

**Issue by shineworld** [EtheaDev/SVGIconImageList#177]
With the TSVGIconImage the letter A (text) is showed during file selection (I use your Explorer plug-ing extension on W10) but not in TSVGIconImage preview and in the form rendering.

B text is converted from object to path with Inkscape and it is visible.
Also Lines with |-----| if not converted to path lost the | at beginning and end and only ----- is showed.
[flat_end_mill.zip](https://github.com/EtheaDev/SVGIconImageList/files/6463823/flat_end_mill.zip)

**Comment by pyscripter** [comment]
Pleaser read about the choice of [factories](https://github.com/EtheaDev/SVGIconImageList/wiki/Choice-of-Factories-(Direct-2D-or-GDI-)).

-  The Native Windows D2D does not support text at all.
-  The Pascal factory does support it but the support  is incomplete.
-  The Cairo factory is your best bet for text.

Or you can convert text to path and use any of the above.

**Comment by shineworld** [comment]
Thanks for the reply.
I will convert the unsupported objects to path :)
