### ISSUE TITLE
Taking into account of the "shape-rendering" attribute for rendering images

### ISSUE THREAD

**Issue by syntax68** [EtheaDev/SVGIconImageList#178]
Hi

Can you tell me if the "shape-rendering" attribute is used or not for rendering SVG images, please? It seems not.
Indeed, when I display a simple grid (Delphi Engine TSVG), the lines present an anti-aliasing effect even if the "shape-rendering" attribute is set to "crispEdges".

Is there a development plan for this attribute?

**Comment by pyscripter** [comment]
> Is there a development plan for this attribute?

I am afraid  not.
