### ISSUE TITLE
Color problem with Android Demo

### ISSUE THREAD

**Issue by carloBarazzetta** [EtheaDev/SVGIconImageList#186]
In the SVGIconImageListDemoFMX, when compiled in Windows 64bit the icon colors are correct, but compiling in Android 64bit the color are not correct.
![image](https://user-images.githubusercontent.com/7803548/126011624-2a2233b5-87d5-4e69-99e9-634f3af98cc6.png)
The conversion from TAlphaColor to TColor32 is made by this function:
```
function AlphaColor32(AlphaColor: TAlphaColor): TColor32;
var
  res: TARGB;
begin
  res.A := TAlphaColorRec(AlphaColor).A;
  res.R := TAlphaColorRec(AlphaColor).R;
  res.G := TAlphaColorRec(AlphaColor).G;
  res.B := TAlphaColorRec(AlphaColor).B;
  Result := res.Color;
end;
```
Why the conversion made from Adroid is different?

**Comment by AngusJohnson** [comment]
I suspect that the problem reported here is not Image32 related becuase I've just discovered significant issues with the Image32 SVG code that will prevent it compiling in FMX. (The rest of the Image32 library compiled just fine with FMX but evidently I've got quite a bit of work to make the SVG code FMX compatible.)

**Comment by AngusJohnson** [comment]
I've just now uploaded various bugfixes to Image32 that address these FMX cross-platform issues.
https://sourceforge.net/p/image32/code/ci/master/tree/source/

**Comment by carloBarazzetta** [comment]
Great Job! Thank you very much!
I've fixed my code of AlphaColor32 adding:
{$IFDEF ANDROID}
  Result := SwapRedBlue(Result);
{$ENDIF}
