### ISSUE TITLE
Format parameter type Mismatch

### ISSUE THREAD

**Issue by mWaltari** [EtheaDev/SVGIconImageList#189]
procedure AppendInt(var s: string; val: double);
begin
  s := Format('%s%1.0d ',[s, val]);
end;

I think it should be
s := Format('%s%1.0f ',[s, val]);, // <- because val is double, not integer.

at Image32_SVG_Writer.pas.
  
Could not find Image32 repository/Bug Tracker so hope it gets notified from here.

-Tee-

**Comment by AngusJohnson** [comment]
`Could not find Image32 repository/Bug Tracker so hope it gets notified from here.`

Thanks for the bug report. I'll fix it soon.
Future bug reports are more likely to be noticed here ... https://sourceforge.net/p/image32/tickets/
(and is less likely to annoy the developers of SVGIconImageList 😜).
