### ISSUE TITLE
Backgroud Transparency

### ISSUE THREAD

**Issue by leonbadman** [EtheaDev/SVGIconImageList#195]
Hi, first of all thank you for your wonderful work !!

In your demo, but also in my application, applying a FixedColor, the original background (transparent) going to semi transparent. 
![Schermata del 2021-07-28 15-45-19](https://user-images.githubusercontent.com/60690593/127333078-fafb2017-3ba6-44b2-b7b8-d265556e8623.png)
![Schermata del 2021-07-28 15-44-32](https://user-images.githubusercontent.com/60690593/127333080-c8e80cea-82ff-476e-8cee-17effef5f057.png)

Is this a bug?

Thanx.

Ciao.
L.

**Comment by AngusJohnson** [comment]
I don't really believe this is a TImage32 bug,but it can still be fixed by changing the TImage32.SetRGB method to this ....

```
procedure TImage32.SetRGB(rgbColor: TColor32);
var
  rgb: TARGB absolute rgbColor;
  r,g,b: Byte;
  i: Integer;
  pc: PARGB;
begin
  //this method leaves the alpha channel untouched
  if IsEmpty then Exit;
  r := rgb.R; g := rgb.G; b := rgb.B;
  pc := PARGB(PixelBase);
  for i := 0 to Width * Height -1 do
    if pc.A = 0 then
    begin
      pc.Color := 0;
      inc(pc);
    end else
    begin
      pc.R := r;
      pc.G := g;
      pc.B := b;
      inc(pc);
    end;
  Changed;
end;
```
