### ISSUE TITLE
FixedColor wrong on Android

### ISSUE THREAD

**Issue by leonbadman** [EtheaDev/SVGIconImageList#196]
Hi, I found a new bug: specifying a FixedColor, image uses another color on Android, no problem instead under Windows.

Thanx.
Ciao.
L.

![WhatsApp Image 2021-08-05 at 15 51 59](https://user-images.githubusercontent.com/60690593/128362208-bbb4180a-4a3e-40d2-bc70-13bf958a42ca.jpeg)
![WhatsApp Image 2021-08-05 at 15 51 54](https://user-images.githubusercontent.com/60690593/128362210-fc03995f-66a0-469c-b549-2463d5df5ee3.jpeg)

**Comment by carloBarazzetta** [comment]
Please look at this issue, probably the problem is similar:
https://github.com/EtheaDev/SVGIconImageList/issues/186

**Comment by leonbadman** [comment]
Sorry Carlo, same issue.

Ciao.
L.
