### ISSUE TITLE
Out of range error in function TSVGIconImage.SVGIconItem

### ISSUE THREAD

**Issue by luebbe** [EtheaDev/SVGIconImageList#198]
I have a strange error which I don't understand.

on a form I have a TSVGIconImage. In FormCreate I assign the imagelist and -index as follows:

```pascal
  svgArrow.ImageList := dmResources.imlEnabledButtons;
  svgArrow.ImageIndex := cImgRight;
```

When this image should be painted I receive an "Out of range exception" in
```pascal
function TSVGIconImage.SVGIconItem: TSVGIconItem;
var
  {$IFDEF D10_3+}
  LVirtualImageList: TVirtualImageList;
  LItem: TVirtualImageListItem;
  {$ENDIF}
  LSVGIconItems: TSVGIconItems;
begin
  Result := nil;
  if FImageList is TSVGIconImageListBase then
  begin
    LSVGIconItems := TSVGIconImageListBase(FImageList).SVGIconItems;
    Result := LSVGIconItems[FImageIndex];
  end;
  {$IFDEF D10_3+}
  if (FImageList is TVirtualImageList) then
  begin
    LVirtualImageList := TVirtualImageList(FImageList);
    if LVirtualImageList.ImageCollection is TSVGIconImageCollection then
    begin
      LSVGIconItems := TSVGIconImageCollection(LVirtualImageList.ImageCollection).SVGIconItems;
      LItem := LVirtualImageList.Images[FImageIndex];
      if Assigned(LItem) then
        Result := LSVGIconItems[LItem.Collectionindex]; <--- Exception here, because LItem.CollectionIndex = -1
    end;
  end;
  {$ENDIF}
end;
```
because LItem.CollectionIndex = -1 

When I initialize the icon with
```pascal
  svgArrow.ImageList := dmResources.imlEnabledButtons;
  svgArrow.ImageIndex := cImgRight -1;
```
the icon is painted.

How can it happen that the collectionindex is -1?
Is there perhaps a problem with the icon name, because it is similar to a standard property? There must be something to it, because the exception also happens with icons named "Top" or "Right".
I only access icons by index, never by name.

**Comment by luebbe** [comment]
Until now I found out that this is also a very nasty side effect of the combination of gettext translation and SVGIconImageList. When I switch the application's language to English, everything is fine.

**Comment by luebbe** [comment]
Added information to the "Known issues" Wiki page

**Comment by pyscripter** [comment]
> The solution is again to put a component on gettext's ignore list:
> 
> `TP_GlobalIgnoreClass(TVirtualImageList);`

I have been using:
`  TP_GlobalIgnoreClassProperty(TObject,'ImageName');`

ImageName should not be translated in any Component.

**Comment by luebbe** [comment]
Should I add this to the Wiki https://github.com/EtheaDev/SVGIconImageList/wiki/Known-issues?
I thought it would be better to ignore any property of the List instead of a specific property of any object.

**Comment by pyscripter** [comment]
I tried to "kill many birds with one stone".  ImageName is present in many components (for example CustomButton, MenuItem, Action), and should never be be translated.

**Comment by luebbe** [comment]
ok, I'll add yours as an alternative solution to the Wiki entry
