### ISSUE TITLE
On the demo

### ISSUE THREAD

**Issue by limelect** [EtheaDev/SVGIconImageList#2]
On the demo after changing to any theme memory leak. D10.2.3
![Screenshot - 26_05_2020 , 08_59_45](https://user-images.githubusercontent.com/4199131/82865462-71380f00-9f2f-11ea-9b86-1c52c9c8c0f0.png)

**Comment by carloBarazzetta** [comment]
It's not a memory leak of the SVG components but only of the TTreeView of the demo.
