### ISSUE TITLE
Coordinates in double (PaintTo methods)

### ISSUE THREAD

**Issue by pyscripter** [EtheaDev/SVGIconImageList#20]
In all drawing libraries GDI, GDI+, DirectX  size and coordinates are either Integer (GDI) or Single (GDI+, DirectX).  The use of Double in the PaintTo methods is unnecessary and inefficient (due to the conversions).  

Please replace all Double with Single.

**Comment by mWaltari** [comment]
Just a suggestion, when/if this change is made, would be cool to make some benchmark/measurement is there effect and if is how much it would be. 

Just out of curiosity and for science.

**Comment by carloBarazzetta** [comment]
Resolved into 1.7 version.
