### ISSUE TITLE
Editors for SVGIconImage

### ISSUE THREAD

**Issue by birbilis** [EtheaDev/SVGIconImageList#202]
Should be able to right click an SVGIconImage on the form and load an SVG file to it. 

I see it shows in 3.x a MultiResBitmap child item that has Edit Bitmap Collection, but in that one you can't load SVG files

Also TSVGIconFixedBitmapItem (one exists as child of MultiResBitmap child of SVGIconImage), there's SVG property with no "..." property editor that would allow setting that string by reading some SVG file contents. Worse problem is that the default sting editor there also has limit in length, so can't load bigger / more details SVG image content by hand (and if you'd load it thorugh a "..." button / property editor, not sure if Delphi IDE will truncate when saving the form or not [hopefully not unless you try to edit the string by hand])

**Comment by carloBarazzetta** [comment]
Please give me positive feedback if the new committed version solves this problem.
Thanks for your patience.

**Comment by birbilis** [comment]
Don't see newer version in GetIt. Is one planned soon? Think I had some issues compiling the lib myself last time I had tried

**Comment by carloBarazzetta** [comment]
When the support for SKIA4Delphi is complete... Probably when the new versione of Delphi 11 is available.
