### ISSUE TITLE
Image32 packages with SVGIconImageList

### ISSUE THREAD

**Issue by shineworld** [EtheaDev/SVGIconImageList#206]
Can coexits Image32 Library with SVGIconImageList Library ?

I've updated Image32 to latest 3.4.1 (used for a new package of UI components).
I've updated SVGIconImageList to latest version.

At New VCL application creation the IDE Show this message:
![image](https://user-images.githubusercontent.com/1633598/140903589-685a38c0-d5f6-416b-819b-6c519441bca3.png)

**Comment by carloBarazzetta** [comment]
The only component you need to install into IDE for Image32 lib is TImage32Panel: this component is already included into package SVGImage32Package, so you don't need to install Image32 packages if you already have SVGIconImageList.

**Comment by shineworld** [comment]
Initially, in 2020, I've installed SVGIconsImageList (without Image32 support).
After I've installed Image32 to create new UI-touch components using eithers,
SVGIconsImageList as SVG collection list to Draw SVG parts and Image32 to draw background, borders, etc of new controls.
Mixed either power :)

I do not use TImage32Panel so I can avoid to register the Image32_VCL-Dsgn.
I can remove Image32 package at all and use sources available in SVGIconsImageList.
The only dubts is that at moment they are not aligned (seem Image32 in SVGIconsImageList is more old).

**Comment by carloBarazzetta** [comment]
I constantly maintain Image32 aligned to SVGIconImageList, and every new release I check the compatibility (see for example #205). If your project points to the original Image32\source folder the compiler uses always the latest version of the library.
Please open an issue if you notice some problem on rendering SVG Icon when you are using newest version of Image32.
Thanks.
