### ISSUE TITLE
SVG components was disabled and can't drag when using Android platform

### ISSUE THREAD

**Issue by thealgorithms10** [EtheaDev/SVGIconImageList#207]
I was trying to use svg images for my android app but seems those components was disabled. But components was usable when i change the platforms to Windows. I was trying to install the package in GetIt. 

Screenshots been provided.

Thanks
![SVGIconImageList - Android platform](https://user-images.githubusercontent.com/82137662/142378223-bc986c96-733c-4f2f-b63f-2a352550cd7e.png)
!

**Comment by carloBarazzetta** [comment]
Resolved in version 3.2.0
