### ISSUE TITLE
GetIt Problem in Delphi 10.3.3

### ISSUE THREAD

**Issue by xelnaga64** [EtheaDev/SVGIconImageList#208]
I'm using Delphi 10.3.3. I formerly installed SVGIconImageList 2.x using GetIt. Today, I saw SVGIconImageList 3.0 is listed in GetIt. So I uninstalled the previous 2.x and tried to install 3.0. However it fails. Please see the screenshot.

![getit](https://user-images.githubusercontent.com/39432041/142914525-87e8d4d1-8c6e-4e9b-a75d-19f2c7c8a0bf.png)

Any idea is appreciated.

**Comment by carloBarazzetta** [comment]
The problem appears that GetIt don't compile SVGImage32Package, that contains the new SVG engine Image32... 
I will write to Embarcadero asking to redo the installer but it will take days.
I recommend that you download the project directly from GitHub and install it by hand following these simple instructions.
[https://github.com/EtheaDev/SVGIconImageList/wiki](https://github.com/EtheaDev/SVGIconImageList/wiki)

**Comment by xelnaga64** [comment]
All right. Thank you!
