### ISSUE TITLE
D10.2.3

### ISSUE THREAD

**Issue by limelect** [EtheaDev/SVGIconImageList#21]
![Screenshot - 05_08_2020 , 10_36_02](https://user-images.githubusercontent.com/4199131/89384915-838cb100-d707-11ea-9d47-cac5f106b76e.jpg)
while changing Theme

**Comment by pyscripter** [comment]
This looks like a Vcl.Styles / TTreeview bug.
You get this memory leak when you change styles in the demo.  The treeview nodes are not freed.

**Comment by carloBarazzetta** [comment]
Yes, is not a problem of the components.
