### ISSUE TITLE
Getting size from SVG

### ISSUE THREAD

**Issue by birbilis** [EtheaDev/SVGIconImageList#210]
Does SVGIconImage support AutoSizing from any sizing information in the SVG file? Or does it expose some way to query for the SVG size without parsing the SVGText property content?

**Comment by carloBarazzetta** [comment]
Actually no, because the various engines uses this information internally to draw an image of a requested size on a canvas: you can look at TSVG o Image32 native Delphi engines to see how the extract those information from the SVG Text.
