### ISSUE TITLE
TSVGIconImage: minimal size

### ISSUE THREAD

**Issue by kazuser** [EtheaDev/SVGIconImageList#214]
Hi! Thanks for your library!

I have a little problem with pretty simple SVG:

`<svg width="32" height="32" xmlns="http://www.w3.org/2000/svg"><path d="m11.17242,11.17242l9.65516,9.65516" stroke-width="0.5" stroke="#000"/><path transform="rotate(90 16 16)" d="m11.17242,11.17242l9.65516,9.65516" stroke-width="0.5" stroke="#000"/></svg>`

![close](https://user-images.githubusercontent.com/3335273/151317294-ca8bf3c7-0aba-4deb-83f2-c680c6f64276.svg)

Edge:
![image](https://user-images.githubusercontent.com/3335273/151316522-2d2d5a4e-2be1-41c2-9fb0-2016cae07d7d.png)

Delphi:
![resize](https://user-images.githubusercontent.com/3335273/151317139-0f758581-9217-4840-83c7-8d203c97f163.gif)

Is there any way to change the minimum allowed size?

**Comment by carloBarazzetta** [comment]
Yes, it's a problem using default engine "Image32": I've sent to Angus Johnson an email to solve this, please wait for a solution.
If you try to use TSVG engine the icon appears correctly but you can have another problems as explained [here:](https://github.com/EtheaDev/SVGIconImageList/wiki/Choice-of-Factories)

**Comment by carloBarazzetta** [comment]
Please give me positive feedback if the new committed version solves this problem.

**Comment by kazuser** [comment]
Thanks a lot, Carlo! Now everything is perfect!

![0](https://user-images.githubusercontent.com/3335273/154704874-f015e86a-69e1-4550-bd7d-9949034c1544.gif)

p.s.
WrapMode = Original
