### ISSUE TITLE
Svg not rendered 

### ISSUE THREAD

**Issue by pyscripter** [EtheaDev/SVGIconImageList#22]
The attached svg is parsed but not rendered properly.
[Back2.zip](https://github.com/EtheaDev/SVGIconImageList/files/5031587/Back2.zip)

**Comment by carloBarazzetta** [comment]
Ok, but I'm not the author of the svg engine so is not easy to correct. For example the use of "transform" and "translate" sometimes fails...
Look into icons folder  Demo\flat-color-icons (extracted from excellent library Icons 8) or other free icons made by Papirus... Sometimes it'more easy to search an alternative icon ;-)
