### ISSUE TITLE
Blueish tint on Android and MacOS-X

### ISSUE THREAD

**Issue by birbilis** [EtheaDev/SVGIconImageList#229]
I see blueish tint on Android when using the latest TSVGIconImageList from GetIt Package Manager

Windows:
![TortoiseAndTheHare_EditMode_StructureView en](https://user-images.githubusercontent.com/3461504/168492935-049ea4c0-c637-4df7-8364-c6911d786bcb.png)

Android:
![Tortoise and the Hare en_StructureView_EditMode-Samsung Galaxy Tab S8-12 0](https://user-images.githubusercontent.com/3461504/168492921-cedff9a7-280e-4029-a360-0ea6f10d12c0.png)

The app is at https://github.com/zoomicon/READCOM_App

Apart from using TSVGIconImage for the SVG images in the stories, I use TSVGIconImageList for the app icons. All those are tinted. However, stories that contain bitmap images show fine, so it's something with the SVG rendering

I think it uses Image32 for rendering now (judging from a little debugging). Is there any known issue with that?
How can I tell your library to use Skia SVG renderer instead? (or is there other engine alternative on Android too?) Do I need to install Skia4Delphi too and right click my project and enabled Skia (to added needed lib to deployment)?

UPDATE:
the same tint appears on MacOS-X (those are supposed to be English/Greek/Italian/Portuguese/Spanish flags in the image)
![image](https://user-images.githubusercontent.com/3461504/169277578-25dbbe55-ffdc-44d7-8615-311e13b36523.png)

Is it something related to RGB versus BGR? Is Image32 also being used by default on OS-X?

**Comment by birbilis** [comment]
Note that bitmap images (rendered via FMX) look fine
![image](https://user-images.githubusercontent.com/3461504/169350732-1a9d7766-7f74-4c86-ad04-68ad493071a6.png)

**Comment by carloBarazzetta** [comment]
Please try to restore previous version of Img32.SVG.Reader that contains:
```
    if (fillColor = clCurrent) then
      {$IF Defined(MACOS) or Defined(MACOSX)}
      drawDat.fillColor := SwapRedBlue(thisElement.fReader.currentColor)
      {$ELSE}
      drawDat.fillColor := thisElement.fReader.currentColor
      {$IFEND}
    else if (fillColor <> clInvalid) then
      {$IF Defined(MACOS) or Defined(MACOSX)}
      drawDat.fillColor := SwapRedBlue(fillColor);
      {$ELSE}
      drawDat.fillColor := fillColor;
      {$IFEND}
    if fillOpacity <> InvalidD then
      drawDat.fillOpacity := fillOpacity;
    if (fillEl <> '') then
      drawDat.fillEl := fillEl;
    if (strokeColor = clCurrent) then
      {$IF Defined(MACOS) or Defined(MACOSX)}
      drawDat.strokeColor := SwapRedBlue(thisElement.fReader.currentColor)
      {$ELSE}
      drawDat.strokeColor := thisElement.fReader.currentColor
      {$IFEND}
    else if strokeColor <> clInvalid then
      {$IF Defined(MACOS) or Defined(MACOSX)}
      drawDat.strokeColor := SwapRedBlue(strokeColor);
      {$ELSE}
      drawDat.strokeColor := strokeColor;
      {$IFEND}

```
because it was lost during update to Image32 4.11 version.
Then give me a feed-back if it works, so i can restore this fix and notify Angus Johnson, the author of Image32.
Thanks.

**Comment by birbilis** [comment]
problem is I'm using the GetIt version (not sure if GetIt allows one to rollback to previous versions). Can I patch it by including my copy of that unit (I can get it from their version control) in the uses clause of the app? I haven't tried building your library, was afraid I'd lose time trying to pull in all dependencies

**Comment by birbilis** [comment]
another problem I see is that this code (which looks promising btw) check if it's targetting MACOS-X, but I don't see Android or iOS mentioned (at Android it's the same issue and I suspect it's on iOS too).

**Comment by carloBarazzetta** [comment]
Unfortunately, I don't have mobile devices on which to test. I advise you to install the library by cloning the repo from Git: the installation is simple, just open the package group do the build / install of the packages, as explained [here](https://github.com/EtheaDev/SVGIconImageList/wiki):
Now you can develop by compiling the sources directly and trying to make changes to fix the color problem on the different devices.

There is another place to adjust color that affect also ANDROID platform, into FMX.Image32SVG:
``` Delphi
function AlphaToColor32(AlphaColor: TAlphaColor): TColor32;
var
  res: TARGB;
begin
  res.A := TAlphaColorRec(AlphaColor).A;
  res.R := TAlphaColorRec(AlphaColor).R;
  res.G := TAlphaColorRec(AlphaColor).G;
  res.B := TAlphaColorRec(AlphaColor).B;
  Result := res.Color;
{$IF Defined(ANDROID) or Defined(MACOS) or Defined(MACOSX)}
  Result := SwapRedBlue(Result);
{$IFEND}
end;
```

**Comment by birbilis** [comment]
thanks, will take a look

btw, an easy way to test is to upload an APK at
https://www.browserstack.com/android-testing

**Comment by birbilis** [comment]
Looking at that code, it seems they were loading the RGB as BGR (but only on OS-X) and then they were swapping again back to RGB or something (this time both on Android and OS-X).

So their original code (without the code that was removed from the SVG loader) would work on OS-X (had double inversion that was self-canceling), but on Android I guess. Now that they removed that they have it broken both on OS-X and Android (then probably on iOS it may work, will check on the iOS emulator)

**Comment by birbilis** [comment]
Started looking at it, one quick comment I have is that I feel the .groupproj should contain the demo projects too for convenience (so that one can easily test a change they did), or could add extra groupproj with everything (packages and demos), since the existing is called "SVGIconImageListGroupPackages". Not sure if GetIt needs that groupproj to only contain the packages or something, plus hope if extra is added with everything that GetIt isn't confused (e.g. losing time to build all demos or something)

**Comment by birbilis** [comment]
I can confirm that the issue occurs on Android with the SVGIconImageListDemoFMX project too (here I project via Miracast [wifi] from Android to Windows 11):

![image](https://user-images.githubusercontent.com/3461504/170021113-0c261f4a-43b6-4b73-9cfc-3edcd6abf712.png)

(I also notice some layout glitch at the FixedColor checkbox and the color dropdown [and its dropdown arrow] under it)

To build/run on Android, I had to right click the Libraries not and select "Revert System Files to Default":

![image](https://user-images.githubusercontent.com/3461504/170019554-0be415ea-4ddb-4cf1-b3cc-b4a3a1434b28.png)

**Comment by birbilis** [comment]
the issue isn't probably with loading the SVGs, but with rendering them, since if I play with the Fixed Color, I see other color result (though I'm not sure how the Fixed Color functionality is implemented [if it "reloads" the SVG from a modified source or if it changes it in memory without invoking an SVG reader/parser again]):

![image](https://user-images.githubusercontent.com/3461504/170021786-ba349ed7-7a8b-4c7f-ab5e-53acef3705b4.png)

**Comment by birbilis** [comment]
making AlphaToColor32 not call SwapRedBlue didn't work, but making SwapRedBlue don't do anything did work:

```
function SwapRedBlue(color: TColor32): TColor32;
var
  c: array[0..3] of byte absolute color;
  r: array[0..3] of byte absolute Result;
begin
  result := color;
  //r[0] := c[2];
  //r[2] := c[0];
end;
```

probably though that method is needed to be there (don't want to make it do nothing), so will look into it a bit more to see who calls it

**Comment by birbilis** [comment]
searching for the symbol with find in files gives:

opening one by one seems actual callers are these methods:
* RgbToHsl at  Img32.pas(1229)
* HslToRgb at  Img32.pas(1292)
* AlphaToColor32 at FMX.Img32SVG.pas(83) - commenting it out there didn't do the trick as I mentioned above
and the most suspicious one:
* UTF8StringToColor32 at Img32.SVG.Core.pas(1191)

fixing the last one also does the trick (instead of making SwapRedBlue do nothing), but it has a conditional check for Android only, so have to check why MacOS-X also has the issue and if this fixes it for it too, or it needs fix also at other place

**Comment by birbilis** [comment]
note that just adding to SVGIconImageListDemoFMX project the patched Img32.SVG.Core.pas does the trick even with the GetIt version of SVGIconImageList

`{$IFDEF ANDROID}
  //color := SwapRedBlue(color); //TODO: this fixes Blueish SVG color tint (RGB-BGR substitution) on Android, but should try to fix OS-X too (https://github.com/EtheaDev/SVGIconImageList/issues/229) - haven't tried iOS yet
{$ENDIF}`

**Comment by AngusJohnson** [comment]
> forwarded the issue to Angus Johnson, author of Image32...

Thanks Carlo.
I'm not doubting there's a problem, but I can't duplicate it, at least when just using Image32.
I've attached a very simple demo FMX app that just uses Image32.
And here are the Windows and Android screenshots:

![fmx_svg_win](https://user-images.githubusercontent.com/5280692/170148028-7d43e9af-d9e8-407d-aa20-71d2737ecd3f.png)

![fmx_svg_and](https://user-images.githubusercontent.com/5280692/170148042-3058d215-f7ef-4450-982d-d0001dbe32e0.jpg)

[fmx_svg_demo.zip](https://github.com/EtheaDev/SVGIconImageList/files/8766846/fmx_svg_demo.zip)

**Comment by AngusJohnson** [comment]
I'm now wondering if this problem is due to a conflict between Image32 and Carlo's [FMX.Image32SVG](https://github.com/EtheaDev/SVGIconImageList/blob/master/Source/FMX.Image32SVG.pas) unit.

As you've observed above, Image32 adjusts swaps the red and blue channels when the precompiler directive ANDROID is defined. However, I note Carlo's  `AlphaToColor32` function (line 72) calls [`TAlphaColorRec`](https://docwiki.embarcadero.com/Libraries/Sydney/en/System.UITypes.TAlphaColorRec) which also switches these color channels depending on endianness. IOWs, I suspect the blue and red channels are being swapped twice.

**Comment by birbilis** [comment]
Hi, if you don't see the issue in Image32 demos (didn't notice any in the version included in SVGIconImageList repo), but only happening in SVGIconImageList FMX demos (and in my app that uses that library), then it's definitely something added there or some difference in the files they have.

So, since there was another suspisious thing in that code, I think I found it.

My original fix showed ok:
![image](https://user-images.githubusercontent.com/3461504/170236744-d54961ec-47b6-40ea-8815-d2d8a8117f3a.png)

but not the FixedColor functionality of that demo, it was broken:
![image](https://user-images.githubusercontent.com/3461504/170236855-bbcf9194-ece7-4794-91c8-5c7fd36546d4.png)

so I went back to the code, first of all had checked the method you had mentioned and though it was being called a lot in the debugger (had breakpoint to confirm I had overriden it with my added changed unit in the demo project), it wasn't affecting the tint issue (whether I had my other fix added or not, it didn't affect something [apart maybe from the FixedColor I mention, didn't try that with it])

the correct (that solves both the tint and the FixedColor functionality) fix is here:
![image](https://user-images.githubusercontent.com/3461504/170238453-304fbcf8-8f84-456c-8f87-6cf7c439c314.png)
at the [FMX.Image32SVG](https://github.com/EtheaDev/SVGIconImageList/blob/master/Source/FMX.Image32SVG.pas) file of SVGIconImage repo

**Comment by birbilis** [comment]
to recap, ignore my originally proposed fix, the issue is in FMX.Image32SVG
@carloBarazzetta please do this fix, tried on both Windows and Android (the R-B color channel reversal goes away and the FixedColor switch works fine too in both)

Since I had observed the issue on OS-X, added OS-X too. However I have some issue with that demo to add OS-X target, fails to compile due to some file rights (can't write to the bin folder etc.). On my READCOM_App project OS-X target builds fine, so will check there too that the fix works on OS-X and let you know

Will also try on iOS Simulator soon (I hope) to see if the issue was ever there for that platform too

**Comment by birbilis** [comment]
since it's a major bug if you could release on GetIt a new version it would be great (just wait for me to check on iOS too)

**Comment by AngusJohnson** [comment]
![image](https://user-images.githubusercontent.com/5280692/170241525-f493f333-4e96-4b5a-8982-69c3839c8f9c.png)

Yes, that may be useful in Image32 too.

**Comment by birbilis** [comment]
I confirmed this fix is fine for my app on Android, but on Mac OS-X it isn't doing the job (I tried both RGBA and BGRA there with no difference which is strange)

The reason might be that some other code that also does reversals and has only check for Android, not Mac OS-X (or vice-versa). In fact there's a chance there are too many reversals happening that could be avoided. 

PAServer is quite slow to deploy to remote Mac, so not easy to try alternatives (takes some time)

Plus had seen some Image32 code that was getting the TPixelFormat from BitmapSurface, not sure what that was about, but maybe one could avoid conditional defines and just get the PixelFormat from the device canvas (though I'm not sure if that is accessible early in the app startup)? e.g. would Android on Intel platforms be using other pixel format that Android on ARM? (not that Delphi can target Android on Intel currently, but Windows is moving onto ARM too so we might have issues with that too in the future if MS doesn't handle such things under the hood)

Another thing is that I don't see MACOSX symbol at
https://docwiki.embarcadero.com/RADStudio/Alexandria/en/Conditional_compilation_(Delphi)
is it for FreePascal or something? I only see a newer one called OSX, but I guess best is to use older MACOS one (and just that if only targetting Delphi). Just in case I tried the fix with OSX symbol (my taget is Mac 64-bit [Intel CPU, an older iMac]), does the same

**Comment by birbilis** [comment]
Just remembered at UTF8StringToColor32 at Img32.SVG.Core.pas(1191) it was only reversing for Android, probably it needed to reverse for OS-X too so that the Copy Image32 to Bitmap other fix will then work. Fingers crossed, will try

**Comment by birbilis** [comment]
Indeed, it worked with this extra fix (this time at Image32's Img32.SVG.Core), aka to have near the end of UTF8StringToColor32 do color reversal for both Android and MacOS-X

an issue is that Image32 was using {$IFDEF ANDROID}...{$ENDIF} instead of {$IF Defined(Android)}...{$IFEND} (note the IFEND btw)

I used this but not sure if it compiles on FreePascal/Lazarus, plus see my question on what MACOSX symbol is (that Carlo uses in his code):
![image](https://user-images.githubusercontent.com/3461504/170250917-c082c3c2-0d45-40ac-a5ab-ad092c6a651e.png)

**Comment by birbilis** [comment]
will update the pull request if still open to have the fixes for both Android and OS-X or else make new one

**Comment by birbilis** [comment]
btw, regarding the use of IFEND, it's required by older compilers if one use $IF (newers accept $ENDIF from what I see). If compiler has issues it's mentioned that one can add
{$IF CompilerVersion >= 24.0 }
  {$LEGACYIFEND ON}
{$IFEND}
https://docwiki.embarcadero.com/RADStudio/Alexandria/en/Legacy_IFEND_(Delphi)
https://stackoverflow.com/a/38052789/903783

**Comment by birbilis** [comment]
also note I tested on "Android on ARM" and "MacOS-X on Intel" targets

**Comment by AngusJohnson** [comment]
> an issue is that Image32 was using {$IFDEF ANDROID}...{$ENDIF} instead of {$IF Defined(Android)}...{$IFEND} (note the IFEND btw)
> 
> I used this but not sure if it compiles on FreePascal/Lazarus, plus see my question on what MACOSX symbol is (that Carlo uses in his code):

I've just fixed this but now I'm having problems uploading to Sourceforge.

**Comment by AngusJohnson** [comment]
I'm still having problems with SourceForge and have decided to move the repository over to GitHub.
(This was something I'd been considering for a while but with the issues I'm currently having with SF has prompted me to move to GitHub immediately. Besides, I have other repositories there.)
Anyhow, [**Image32**'s updated code can be found here](https://github.com/AngusJohnson/Image32).

**Comment by birbilis** [comment]
will probably need to use that LEGACYIFEND code block I mentioned above to stop emitting warning for the use of the legacy IFEND (unless one doesn't care about older compilers that needed IFEND to match IF), else will get:
* SVGIconImageList\Source\FMX.Image32SVG.pas(83,3): warning H2586: H2586 Legacy '$IFEND' directive found. Consider changing to '$ENDIF' or enable $LEGACYIFEND
* SVGIconImageList\Source\FMX.Image32SVG.pas(177,155): warning H2586: H2586 Legacy '$IFEND' directive found. Consider changing to '$ENDIF' or enable $LEGACYIFEND

**Comment by AngusJohnson** [comment]
> Speaking of older compilers (or FreePascal/Lazarus), I'm not even sure the "Defined(symbol)" is supported

I've tested this and it's OK in Delphi 7.

**Comment by birbilis** [comment]
nice, I also see at https://wiki.freepascal.org/$IF that FreePascal supports "$IF Defined

> //But with the {$IF} you can check conditions together: {$if defined(SOMETHING) and defined(SOMETHINGELSE)}//simple and readabl instead of union {$IFDef}`s 

also at https://wiki.freepascal.org/$IF/fr one sees $IFEND is supported (apart from $ENDIF that is used in the English page's example)

so if Delphi 7 supports matching an $IF with an $ENDIF guess one could use $ENDIF instead of $IFEND (and if you don't care for earlier Delphi). Can you check?

else will have to keep $IFEND (to match the $IF) and add the
{$IF CompilerVersion >= 24.0 }
  {$LEGACYIFEND ON}
{$IFEND}

to avoid Delphi 11 warnings about legacy $IFEND

judging from that snippet checking for ver24 of the compiler and that being "Delphi XE3 / C++Builder XE3" at https://docwiki.embarcadero.com/RADStudio/Sydney/en/Compiler_Versions
there's high chance Delphi 7 (if that's your min support target) needs the $IFEND

**Comment by birbilis** [comment]
(no need to check, I see "At the XE4 release, the Delphi compilers were changed to accept either $IFEND or $ENDIF to close $IF statements. Before XE4, only $IFEND could be used to close $IF statements." in the doc page on $LEGACYIFEND - so need to have that extra snippet, will add to my pull request (https://github.com/EtheaDev/SVGIconImageList/pull/231) since it's still open.

Not sure if one needs to have it per file, I suppose so. Else when it says it restores old behaviour to require $IFEND would mean it causing issues to other files in same project if one added the .pas files to their project directly

**Comment by AngusJohnson** [comment]
> else will have to keep $IFEND (to match the $IF) and add the
{$IF CompilerVersion >= 24.0 }
{$LEGACYIFEND ON}
{$IFEND}

I'm pretty sure this will be necessary.

**Comment by birbilis** [comment]
thing is I was seeing the warning but not seeing when I try to clean/rebuild. Not sure if only shown when one mixes $IF/$ENDIF and $IF/$IFEND in the same file

However I do see that SVGInterfaces.pas needs to be consistent too and use $IFEND to match $IF (uses $ENDIF). Speaking of consistency it also seems to mix $IF Defined and $IFDEF in that file

![image](https://user-images.githubusercontent.com/3461504/170623404-a076e561-dbd6-477d-a895-7fc9a96ff703.png)

**Comment by birbilis** [comment]
@AngusJohnson please see https://github.com/EtheaDev/SVGIconImageList/issues/233

not sure why, but I had to undo the fix in Img32.SVG.Core.pas (aka only swap for Android, not OS-X) since blue tint reappeared on OS-X (and not Android this time) when trying latest SVGIconImageList. 

I kept the RGBA that I had introduced for OS-X and Android at TFmxImage32SVG.PaintToBitmap (file FMX.Image32SVG.pas of SVGIconImageList repo)
but also had to remove from AlphaToColor32 at same file the swap for OS-X this time (that was there from before)

I wonder if your comment at
https://github.com/EtheaDev/SVGIconImageList/issues/229#issuecomment-1137069733
is related, aka if you added some RGBA similar logic somewhere in Image32 that caused this regression

as I said before, probably someone should look into those byte swaps and if they're actually needed or done multiple times (and just undo their actions)

I tried various alternatives again this time like not using RGBA but stick to BGRA that was originally used at that PaintToBitmap, but didn't help

**Comment by AngusJohnson** [comment]
> I tried various alternatives again this time like not using RGBA but stick to BGRA that was originally used at that PaintToBitmap, but didn't help

I'm afraid I don't have any Mac devices to do testing myself so I'm dependent on feedback from those who do which obviously makes debugging more challenging (and much slower).

Anyhow, when confronted with these sorts of bugs, my first inclination is to identify the components and test each separately. So here I suggest testing Image32 independant of SVGIconImageList. To do that could you compile and run the [simple demo](https://github.com/EtheaDev/SVGIconImageList/files/8767406/fmx_svg_demo.zip) (that I also linked to way above). If the color channels are reversed in the demo (as I suspect) then we've considerably narrowed down where to look for this bug. Cheers A.

**Comment by carloBarazzetta** [comment]
@birbilis, can you test the Image32 simple demo to understand at what level the error can be found?
The pull request you asked me to approve, should it solve the problem?
Thank you very much!

**Comment by birbilis** [comment]
yes it solves it, but just in case let me first check that Image32 standalone demo

**Comment by birbilis** [comment]
not sure you need to reopen this issue - I had added separate issue since the regression was for OS-X only: https://github.com/EtheaDev/SVGIconImageList/issues/233

**Comment by birbilis** [comment]
indeed, the sample project with latest Image32 has blueish tint on OS-X, removing the swap again for OS-X at UTF8StringToColor32 (probably something else was introduced that made it not needed anymore) fixes the issue as shown at https://github.com/AngusJohnson/Image32/issues/4

**Comment by birbilis** [comment]
of course for latest SVGIconImageList the rest of the changes I did at https://github.com/EtheaDev/SVGIconImageList/issues/233 are needed too (think they were already pulled in)

**Comment by birbilis** [comment]
seems Image32 was also broken for Android regarding that tint. To fix it I just did https://github.com/AngusJohnson/Image32/commit/a91336d50962f058ee17940e7b5008974b39ac3e so taking this in mind I will need to do a new PR for SVGIconImageList too. My guess is I'll need to remove all swaps now (even for Android) from AlphaToColor32, will try ASAP

**Comment by birbilis** [comment]
It seems that by fixing the new Image32 to remove that swap not swaps are needed anymore in AlphaToColor32, nor an RGBA instead of BGRA is needed at PaintToBitmap call, for either Android or OS-X. My guess is some recent change to Image32 is using that RGBA under the hood which made the older swaps obsolete

added https://github.com/EtheaDev/SVGIconImageList/pull/235 that should close this issue

**Comment by birbilis** [comment]
btw, noticed the Image32 folder contains an older Img32.Clipper.pas instead of Img32.Clipper2.pas. Also not sure where it's pulling the Clipper units from (Image32 ships them in a subfolder). Probably SVGIconImage32 doesn't use the Clipper or that older Clipper didn't need such extra units?

**Comment by AngusJohnson** [comment]
@birbilis.
Firstly, thank you again for the valuable feedback.
I've just tried [your latest commit](https://github.com/birbilis/Image32) on my Android phone (Samsung Galaxy S20 FE) and I get the red-blue color channels inverted. But when I use my [current Image32 source code](https://github.com/AngusJohnson/Image32) (on the same phone) the colors are correctly displayed. Would you mind rechecking this on your Android device(s)?

**Comment by birbilis** [comment]
Did a pull from my repo (just in case)
Uninstalled SVGIconImageList from GetIt and closed Delphi IDE
Opened the Image32.groupproj on a newly started instance of Delphi 11.1
Made the fmx_svg project Active (it is the one from FMX3/ folder) in the Projects pane
Selected Android 64-bit Target 
Selected Development Configuration
Right clicked Libraries and did "Revert System Files to Default"
Did Project/Build
Did Project/Deploy (have already generated/set a keystore and self-issued certificate to use with Android deployments)
Uploaded .apk from Image32\Examples\FMX3\Android64\Release\fmx_svg\bin to BrowserStack's App Live
Tried that APK with Samsung Galaxy S20 with Android 11

Resulting image is fine:
![image](https://user-images.githubusercontent.com/3461504/177014456-d37c096a-8f74-44fb-bf3d-8de188369ab4.png)

Is there a chance your system is somehow mixing other versions of Image32 units coming from SVGIconImageList? On mine I'm uninstalling from GetIt since I only use Packages and don't set any paths for building

---

Just in case I cleaned and built again all the packages I have in the .groupproj and installed the VCL one, then cleaned the Android target again for the fmx_svg project and built, deployed and uploaded and tried on BrowserStack App Live again, this time on Samsung Galaxy S20 with Android 10 (instead of 11). Had the exact same result so my version shows fine.

---

To be extra sure I also then opened in Project view the Contains/../ node of Img32_FMX.bpl package project (one that I've added to Image32 to only contain the FMX-compatible units and reference [require] the FMX framework) and drag-dropped all the files (also separately did for the ones under the Clipper subfolder there) onto the fmx_svg project node in the Projects view (that is showing the Image32.groupproj). This added direct references to the Image32 units to that project, so I can be pretty sure it's not pulling some other unit version implicitly from elsewhere (that's the way I can also try patches when I work with Getit-installed stuff like SVGIconImageList, I add a direct unit reference to a demo project, and note this time I have SVGIconImageList uinstalled and also work directly on my fork of the Image32 repo). Again this time my version works fine on Google Pixel 6 with Android 12

---

Also note that I've tried the fixes with the SVGIconImageList repo and its copy of Image32 (which uses the old Clipper) separately and its SVGIconImageListFMXDemo works fine with my latest changes (on OS-X and Android). And my app too.

I'll see if I can try on another machine too, however ideally one should try on a Delphi installation where SVGIconImageList had never been installed (just grab my Image32 version, open the groupproj and do the above steps)

**Comment by AngusJohnson** [comment]
Hi again George.
Here are the steps I've taken to test your modifications.
1. Closed Delphi.
2. Renamed my Image32 folder so any preset source and library folders in the IDE referencing Image32 won't be found.
3. Downloaded and unzipped [your latest Image32 commit](https://github.com/birbilis/Image32) to a temporary folder.
4. Opened Delphi IDE again and opened the FMX3 sample in this temporary folder.
5. Connected my phone to my PC using USB.
6. Compiled, installed and executed the app in my phone (ie not using emulation) and you'll see the result below.

![Screenshot_20220703-080903](https://user-images.githubusercontent.com/5280692/177017649-bcbb5261-c2ef-4e30-9f7a-6ef3de785a62.jpg)

![img32_2](https://user-images.githubusercontent.com/5280692/177017676-243ac614-6e17-424f-8cd3-d86f3dda0cf9.png)

![img32_3](https://user-images.githubusercontent.com/5280692/177017680-702a3b92-628d-441b-a4bf-319c739fed41.png)

**Comment by birbilis** [comment]
I don't think renaming is enough if Delphi is for some reason compiling units into some shared folder, or if you have another Image32 installed via a separate package like the one SVGIconImageList from GetIt seems to be installing

the safest way to try it is to add via drag-drop all the needed Image32 source files into the test project so that they're explicitly referenced. Note that I've tried that step too

I'll check in another machine too, but I don't have any machine where SVGIconImageList was never installed or other clean Delphi installation

**Comment by AngusJohnson** [comment]
> the safest way to try it is to add via drag-drop all the needed Image32 source files into the test project so that they're explicitly referenced. Note that I've tried that step too

Yes, fair point. 
Nevertheless, having done as you've suggested I get exactly the same result - reversed red blue colors.

**Comment by birbilis** [comment]
So I went to a laptop of mine that had Delphi 11.0, upgraded it to Delphi 11.1 (this uninstalls all GetIt packages first). Did check in My Documens at Embarcadero\Studio\22.0\CatalogRepository that there are no folders for SVGIconImageList anymore. That machine is not exactly "clean" since I sync My Documents via OneDrive with my main dev machine, however I'm pretty sure it's not pulling any compiled units from the other one.

Synced with my fork of Image32 and built the packages in the groupproj and the demo from FMX3 folder. Uploaded APK file to BrowserStack App Live testing / device cloud (note that is using real devices, not emulators). Shows fine:

![image](https://user-images.githubusercontent.com/3461504/177148994-f5dc2b85-cc90-45cb-b238-1b936388dd59.png)

Can you try the .apk at this link?
https://1drv.ms/u/s!AlQsuVnvuzUjgYKjADi88p43TxDP414?e=gAGhZW

If it shows wrong on your device then it's someother issue (related to hardware acceleration or something). If it shows OK then it means one of us is compiling/linking wrong (different) code

**Comment by AngusJohnson** [comment]
> Can you try the .apk at this link?

Yes, and it looked just fine on my phone. 🤔

**Comment by birbilis** [comment]
I think next best way to try is to rename all Image32 units with some prefix and rename all use clauses too at them and at the demo app (I'll take a look with [grepwin](https://tools.stefankueng.com/grepWin.html))

**Comment by birbilis** [comment]
> Copied the contents from the source folder into Examples/FMX3.

not sure that is enough - what I'm doing is drag-dropping the files (either from the Image32_FMX package project in the group project, or from Windows Explorer) onto the demo project so that it adds in its .dpr direct references to them (of the style uses xx in '..\somefolder\xx.pas').

**Comment by birbilis** [comment]
In the meantime, I also tried downloading the .zip from my fork, opened the groupproj and tried the fmx_svg demo with same good result (this time with 32-bit target) on Google Pixel (Android 8). Then added the Image32 FMX related source files (practically all apart Layers and the Fmt. PNG/JPG/QOI/GIF that seem to need Windows/VCL) to the project as direct references and tried on Google Pixel 6, same result. Then also added the .inc files just in case to the project as direct references (this doesn't seem to change the .dpr, just the .dproj most probably) and tried again the 32-bit Android APK with Google Pixel 5 on BrowserStack. Same good render of SVG.

Can you try changing (temporarily) the fmx_svg .dpr in my repo download to this one? (this uses the direct references I mentoned [to be more certain where it's pulling stuff from]):

```
program fmx_svg;

{$R *.dres}

uses
  System.StartUpCopy,
  FMX.Forms,
  unit1 in 'unit1.pas' {Form1},
  Img32.Clipper2 in '..\..\source\Img32.Clipper2.pas',
  Img32.CQ in '..\..\source\Img32.CQ.pas',
  Img32.Draw in '..\..\source\Img32.Draw.pas',
  Img32.Extra in '..\..\source\Img32.Extra.pas',
  Img32.Fmt.BMP in '..\..\source\Img32.Fmt.BMP.pas',
  Img32.Fmt.SVG in '..\..\source\Img32.Fmt.SVG.pas',
  Img32.FMX in '..\..\source\Img32.FMX.pas',
  Img32.Layers in '..\..\source\Img32.Layers.pas',
  Img32 in '..\..\source\Img32.pas',
  Img32.Resamplers in '..\..\source\Img32.Resamplers.pas',
  Img32.Storage in '..\..\source\Img32.Storage.pas',
  Img32.SVG.Core in '..\..\source\Img32.SVG.Core.pas',
  Img32.SVG.Path in '..\..\source\Img32.SVG.Path.pas',
  Img32.SVG.PathDesign in '..\..\source\Img32.SVG.PathDesign.pas',
  Img32.SVG.Reader in '..\..\source\Img32.SVG.Reader.pas',
  Img32.Text in '..\..\source\Img32.Text.pas',
  Img32.Transform in '..\..\source\Img32.Transform.pas',
  Img32.Vector in '..\..\source\Img32.Vector.pas',
  Clipper.Core in '..\..\source\Clipper\Clipper.Core.pas',
  Clipper.Engine in '..\..\source\Clipper\Clipper.Engine.pas',
  Clipper.Minkowski in '..\..\source\Clipper\Clipper.Minkowski.pas',
  Clipper.Offset in '..\..\source\Clipper\Clipper.Offset.pas',
  Clipper in '..\..\source\Clipper\Clipper.pas';

{$I Img32.inc}
{$R *.res}

begin
{$IFDEF REPORTMEMORYLEAKS}
  ReportMemoryLeaksOnShutdown := true;
{$ENDIF}
  Application.Initialize;
  Application.CreateForm(TForm1, Form1);
  Application.Run;
end.
```

**Comment by birbilis** [comment]
So I did in a copy of my repo fork's unzipped folder a change with grepwin of all Image32 to Image42 and all Img32 to Img42, then via command prompt did
` ren Img32*.* Img42*.*`
and
`ren Image32*.* Image42*.*`
at main folder, at source, source\Packages and at examples\experimental subfolders

then built/deployed 64-bit Android target, see
https://1drv.ms/u/s!AlQsuVnvuzUjgYKpC1wcZOeH5zDh3Rc?e=0hDxji (for the Image42 test folder)
https://1drv.ms/u/s!AlQsuVnvuzUjgYKqEW84651LRu5Rihw?e=ITToG5 (for the resulting APK - make sure you uninstall any instances of that demo from your Android phone first, since I don't change the packagename or version - to be more sure this is the one you run you can also add some visible label to the demo in that Image42 source and rebuild). Have tried the APK on BrowserStack and looks fine again

**Comment by AngusJohnson** [comment]
> Can you try changing (temporarily) the fmx_svg .dpr in my repo download to this one? (this uses the direct references I mentoned [to be more certain where it's pulling stuff from]):

Done, but with the same result.

**Comment by birbilis** [comment]
Then please also try Image42 (and also try the APK I built with it separately). If that APK shows fine but you build one that doesn't from that Image42 folder, then if it's not something strange with h/w acceleration, it could be something with the Delphi version / Firemonkey library you use. I use Delphi 11.1 with both patches installed

**Comment by AngusJohnson** [comment]
> Then please also try Image42 (and also try the APK I built with it separately)

The APK displayed correctly on my phone.

The Image42 code also displayed correctly on Windows but while it compiled and installed on my phone it always crashed before it displayed anything. I tried numerous times in both debug and release modes without success, and I uninstalled the app each time before each compile.

**Comment by birbilis** [comment]
> The Image42 code also displayed correctly on Windows but while it compiled and installed on my phone it always crashed before it displayed anything. I tried numerous times in both debug and release modes without success, and I uninstalled the app each time before each compile.

did you try right-clicking on the Libraries node and selecting to Reset to system defaults?

>while I understand there are currently problems with Image32 on Mac devices, but is it not displaying correctly on your
> Android devices too?

yes, it seems that Image32 demo isn't showing ok on neither Mac nor Android without the fix (actually a removal of those swaps for either platform) in my fork

**Comment by AngusJohnson** [comment]
> I mean do this to reset libraries just in case (btw, which Delphi version are you using? are all patches installed for it?):

Thanks, that got your Image42 running on my phone but still with the wrong colors.
I'm using Delphi 10.4 (Update 2) Community Edition.

> you need to change the Configuration to "Development" instead of "Application Store"

I've never used "Application Store"

This is a long shot but worth trying (as it's likely this issue is due to a change between Delphi 10.4 and 11) ...
In the procedure `AssignImage32ToFmxBitmap` in `Img32.FMX` change the following line
```
  //src := TBitmapData.Create(img.Width, img.Height, TPixelFormat.BGRA);
  src := TBitmapData.Create(img.Width, img.Height, TPixelFormat.RGBA);
```
This has no affect in Delphi 10.4 but it just might fix things in 11. 
And please try this with both my otherwise unaltered Image32 and your forked revision. Cheers.

**Comment by luebbe** [comment]
Interesting to see the problem here and the new discussion in Graphics32 occur at the same time: https://github.com/graphics32/graphics32/issues/199

**Comment by carloBarazzetta** [comment]
No more issue reported, I'm closing...
