### ISSUE TITLE
Icon Categories

### ISSUE THREAD

**Issue by pyscripter** [EtheaDev/SVGIconImageList#23]
It would be nice if TSVGIconItem contained a Category field (possibly empty) and the property editors allowed for filtering by Category.  (Like Actions or the Delphi ImageCollection)

**Comment by carloBarazzetta** [comment]
what is needed is:
A new property 'Category' of TSVGIconItem
Enhancement of the TSVGIconImageCollection editor to set the category of one or more TSVGIconItems (apply a category label to a selection of icons)
filter the icons according to category.

**Comment by carloBarazzetta** [comment]
@pyscripter: I noticed that the "Category" is just a way to "read" the "name" property of the image in a virtualimagelist.
If you try to set in the name property of some TSVGIconItem with category + \ + name (eg "Business\businessman" and "Business \ businesswoman") then the component editor of VirtualImageList automatically recognizes the category "Business".
For this reason I suppose we don't need a new Category property, but only extends the component editor of svgcollection / svgimagelist with a listview for grouping "Categories" and a "Set Category ..." button as in the standard ImageEditor of ImageCollection. Do you agree?

**Comment by pyscripter** [comment]
Yes, that should be fine.

**Comment by carloBarazzetta** [comment]
I'm working on a new layout for the component editor, similar to ImageCollection Editor, this is a preview.
![image](https://user-images.githubusercontent.com/7803548/91070098-97587280-e636-11ea-9012-9092aeaaa58c.png)
Give me some feedbacks... thanks.

**Comment by pyscripter** [comment]
This looks great!  I can't wait!

**Comment by carloBarazzetta** [comment]
Committed/Pushed now!
