### ISSUE TITLE
SVGIconImageListDemoFMX can't build when both Android and OS-X platforms are added

### ISSUE THREAD

**Issue by birbilis** [EtheaDev/SVGIconImageList#232]
Seems SVGIconImageListDemoFMX tries to place its build output into
......\My Documents\Embarcadero\Studio\22.0\CatalogRepository\SVGIconImageList-11-3.9.1\Demo\Bin

which for OS-X makes a SVGIconImageListFMX (with no extension) file
but for Android tries to make an SVGIconImageListFMX subfolder
and Windows doesn't allow a file and folder with same name to co-exist (have to delete one or the other first to build for the other platform)

Note that I'm just adding the MacOS-X 64-bit platform to the project without doing any other configuration

**Comment by birbilis** [comment]
![image](https://user-images.githubusercontent.com/3461504/175777657-0eaab205-096d-4003-9b1c-dced0afc82d1.png)

**Comment by carloBarazzetta** [comment]
have no idea, because I can't test the build with platforms like iOS and OSX.
If you can prepare a correct project file for all platforms, please send me a copy...

**Comment by carloBarazzetta** [comment]
Is this problem resolved?

**Comment by carloBarazzetta** [comment]
Please try to change Image32.inc adding {$IFDEF MSWINDOWS} surrounding of {$DEFINE USING_VCL_LCL} as in this example:

```
{$IFDEF MSWINDOWS}
  {$DEFINE USING_VCL_LCL}
{$ENDIF}

```

**Comment by carloBarazzetta** [comment]
Fixed in latest version.
