### ISSUE TITLE
use Clipper2 instead of Clipper as in official Image32 repo

### ISSUE THREAD

**Issue by birbilis** [EtheaDev/SVGIconImageList#236]
noticed the Image32 folder contains an older Img32.Clipper.pas instead of Img32.Clipper2.pas. Also not sure where it's pulling the Clipper units from (Image32 ships them in a subfolder). Probably SVGIconImage32 doesn't use the Clipper or that older Clipper didn't need such extra units? 

if SVG rendering as used by SVGIconImageList does make use of the Clipper, then Clipper2 is faster from what I understand from its repo at https://github.com/AngusJohnson/Clipper2 - it also included in source/Clipper subfolder at Image32 repo (guess it has the latest, but could have used a subrepo folder instead to point to the Clipper repo to maintain in one place)

**Comment by carloBarazzetta** [comment]
Done.
