### ISSUE TITLE
SVGIconImageList 3.9.1 says "VCL _FMX" instead of "VCL & FMX"

### ISSUE THREAD

**Issue by birbilis** [EtheaDev/SVGIconImageList#237]
![image](https://user-images.githubusercontent.com/3461504/177040882-092df773-5910-4cb1-936a-7df080734553.png)

Not sure if that's the reason it shows twice (none of those are installed), I do see Skia4Delphi twice there too
This is not the machine I use regularly, plus I use OneDrive to sync documents folder with my main machine, not sure if that can cause any hickups with Delphi GetIt Package Manager

The title looks problematic though (with _ and missing space instead of & )

**Comment by birbilis** [comment]
did install of that 3.8 and just said process completed succesfully, then uninstalled it.

then installed 3.9.1 (the one with the issue in its title) and it's interesting that when intalling its title shows ok (in the past I think it was showing &&, not doesn't show _ but &, even though in GetIt's list it's with _ )

![image](https://user-images.githubusercontent.com/3461504/177041659-2e86be30-619d-43e0-9ad5-75952552b9c8.png)

now 3.8 doesn't show anymore, probably related to OneDrive syncing files (Documents folder backing up to cloud), think it was internally considering it installed / Delphi was loading it, but GetIt's list was failing to mark it correctly (probably keeps some cache/db of what user had manually installed on that machine). Same case must be with Skia4Delphi in that screenshot showing twice

**Comment by birbilis** [comment]
uninstalling and reinstalling 3.9.1 again also gets rid of the warning about Img32.Vector.pas not being found that was shown above

![image](https://user-images.githubusercontent.com/3461504/177041850-c724e996-6ee6-4785-b38f-5cebfb6536cc.png)

**Comment by carloBarazzetta** [comment]
I've no control over GetIt installation process...

**Comment by carloBarazzetta** [comment]
Resolved with latest GetIt deploy
