### ISSUE TITLE
Firemonkey SVGIconImageList Editor wrong placement

### ISSUE THREAD

**Issue by birbilis** [EtheaDev/SVGIconImageList#238]
Firemonkey SVGIconImageList Editor shows at bottom of screen instead of center and under the Windows Taskbar
Result is the user doesn't know there is OK button they have to press (if they press [X] at the top they do cancel - that could ask them when there are changes whether to keep them or not)

In this image I moved the dialog up a bit, in my case (a laptop with 16:9 15.8" screen) the bottom buttons where hidden

Should maybe center it instead (might still have issue for smaller monitors), or align to top of screen, or ask Delphi to give screen size without the taskbar (I think it had some way to give that - though it may have been for VCL only)

![image](https://user-images.githubusercontent.com/3461504/178106139-7f4b2589-5e3b-4804-b328-f16cfdaff3b6.png)

**Comment by carloBarazzetta** [comment]
The component is redesigned to select fixed color from a color palette.
