### ISSUE TITLE
[Wiki] Idea: Include units instead of Source Code as alternative description in wiki

### ISSUE THREAD

**Issue by rifoerster** [EtheaDev/SVGIconImageList#242]
I keep running in problems in Components when including the Source code directly, instead of the units. (Probably because of different Projects settings, but hard to tell with Delphi). 

When including the Units itself it perfectly works every time (with the added boni that the units don't get recompiled for no reason).

I added them as following: {DevDirectory}\D11\$(Platform)\$(Config)

**Comment by carloBarazzetta** [comment]
Are you using this components from Git o from GetIt?
if you are using library from Git, when you build packages, all dcu units are compiled into:
{SVGIconImageListFolder}\Lib\D11$(Platform)$(Config)
You can set the search path of your project to this folder, so there is no need to recompile them ...

**Comment by carloBarazzetta** [comment]
Yes you are right. I will update the WIKI documentation

**Comment by carloBarazzetta** [comment]
Done!

**Comment by rifoerster** [comment]
This is awkward on my part. When pasting the directory here, something must have gone wrong: 
The directory is `{DevDirectory}\Lib\D11\$(Platform)\$(Config)`. ( Depending on Delphi Version of cause). 

Sorry.

![grafik](https://user-images.githubusercontent.com/45009331/188433944-06599a44-0da2-43dd-82e8-8783aad9ac16.png)
