### ISSUE TITLE
TSVGIconImageCollection not work in FMX

### ISSUE THREAD

**Issue by kabiri** [EtheaDev/SVGIconImageList#246]
when i add TSVGIconImageCollection to FMX form delphi add Vcl.BaseImageCollection to unit

**Comment by carloBarazzetta** [comment]
Yes, because you must use TSVGIconImageList for FMX (look at SVGIconImageListDemoFMX).
TSVGIconImageCollection is a VCL component used to combine a collection of SVG images and VirtualImageList.

**Comment by kabiri** [comment]
becase TSVGIconImageList don`t have SVGText property i use TSVGIconImageCollection.
i can not use "SVGIconImageList1.Source[7].SVGText"
"SVGIconImageCollection1.SVGIconItems[7].SVGText"

**Comment by carloBarazzetta** [comment]
You can use:
function TSVGIconImageList.InsertIcon(const AIndex: Integer;
  const ASVGText: string; const AIconName: string = ''): TSVGIconSourceItem;

**Comment by kabiri** [comment]
i want get SVGText of icon.

**Comment by carloBarazzetta** [comment]
with 
  LIconItem: TSVGIconItem;
  LList: TSVGIconImageList;
you can:  
LIconItem := LList.SVGIconItems[Index];
SvgText := LIconItem.SVGText;
Look into SVGIconImageListEditorUnit, the component editor, to explore how to use TSVGIconImageList

**Comment by kabiri** [comment]
ok
thanks
