### ISSUE TITLE
Cant manually Install on D11, W11

### ISSUE THREAD

**Issue by ZaakaJarimbo** [EtheaDev/SVGIconImageList#247]
I keep getting the following error when trying to install
![image](https://user-images.githubusercontent.com/5955746/200315956-08bf50a2-e9fb-4c61-8724-f252ea642750.png)

Am i missing something?

**Comment by carloBarazzetta** [comment]
Are you installing packages from Git-Hub or from GetIt?
If you are using Github repo, I've updated now the installation documentation: you must open the package group from \svgIconImageList\Packages\D11\SVGIconImageListGroupPackages.groupproj, then buil all run-time packages and install design time packages.

**Comment by ZaakaJarimbo** [comment]
Installing from GitHub, sorry I am new to adding packages etc, normally use DELPHI in Vanilla, I take it that the run-time packages start with SVG and the design time packages start with dcl

**Comment by carloBarazzetta** [comment]
Did you built the packages with my instructions? can i close this issue?
