### ISSUE TITLE
TSVGIconImage - something wrong with colors?

### ISSUE THREAD

**Issue by kazuser** [EtheaDev/SVGIconImageList#248]
Could you please explain, what's going on with white color?

It looks ok in design-time (_in preview_):
![image](https://user-images.githubusercontent.com/3335273/204524447-4665a1cb-690c-42a9-9fb5-d8c7b92af7e6.png)

but not in run-time:
![image](https://user-images.githubusercontent.com/3335273/204524492-f3d621f1-dfe8-4e03-baeb-0dfbf8b0b8d6.png)

Test project: [Project1.zip](https://github.com/EtheaDev/SVGIconImageList/files/10112814/Project1.zip)

p.s.
Yep, I know it's funny but I need 100,00% accuracy, not 99,999% 🥲

**Comment by TommiPrami** [comment]
Must be due the antialiasing. Can it be disabled for testing?

**Comment by luebbe** [comment]
You beat me to it by a few seconds @carloBarazzetta  :)

**Comment by kazuser** [comment]
Ok, how to disable "antialiasing"? I see "Disable Interpolation" only.

**Comment by kazuser** [comment]
I using with defaults settings.

Could you please try my sample (is in a zip-file in first message) and confirm/refute wrong color?

**Comment by carloBarazzetta** [comment]
have no control over the antialiasing effect applied by the SVG-Engine being used. You can test with a circle instead of an 'X' so that the center pixel can't be affected by antialiasing.
