### ISSUE TITLE
TSVGIconImage - more properties

### ISSUE THREAD

**Issue by kazuser** [EtheaDev/SVGIconImageList#249]
Could you please add more properties for **TSVGIconImage** (like in [FMXUI](https://github.com/yangyxd/FMXUI)):

![image](https://user-images.githubusercontent.com/3335273/204995533-710d7f26-20a9-4934-a595-5caa300b7c92.png)

Very useful for using multiple SVG in different states and in one control.

**Comment by carloBarazzetta** [comment]
I'm sorry but I have no plans to expand FMX components in the near future...
