### ISSUE TITLE
TSVGIconImage - broken ShowHint

### ISSUE THREAD

**Issue by kazuser** [EtheaDev/SVGIconImageList#250]
![TSVGIconImage](https://user-images.githubusercontent.com/3335273/205088038-eaf02802-68b6-4d6e-aac6-d35410298321.gif)

**Comment by carloBarazzetta** [comment]
If you look at TSVGIconImage class in FMX.SVGIconImage.pas unit you can see that I haven't defined anything on Hint. My component inherits from TImage, so I assume the problem is in TImage class...
