### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by marc-odp** [EtheaDev/SVGIconImageList#253]
D11. I compiled all the packages. No error.
After that I try 'install' of the 2 design time packages and I get this error ...
![image](https://user-images.githubusercontent.com/17361839/219876689-cab93620-82f6-4b09-87b4-e1aa1b1dac5d.png)

**Comment by carloBarazzetta** [comment]
Are you using: SvgIconImageList\Packages\D11\SVGIconImageListGroupPackages.groupproj ?
Try to close/reopen IDE then first "build" dcl packages and then "install".
Do you have also Image32 library already installed?

**Comment by carloBarazzetta** [comment]
Probably its was a problem with Skia4Delphi sources and dll, try with latest version.
