### ISSUE TITLE
SvgIconImage.DoubleBuffered := True;

### ISSUE THREAD

**Issue by limelect** [EtheaDev/SVGIconImageList#255]
D10.2.3
compiling svgExplorer
No DoubleBuffered in SvgIconImage.

Window 7
On the SvgViewer window svg support is not available

On svgexplorer scale does not exist

**Comment by carloBarazzetta** [comment]
I'll investigate, but SvgIconExplorer is an old way to obtain preview of svg icons into file-system.
Consider to use: https://github.com/EtheaDev/SVGShellExtensions

**Comment by carloBarazzetta** [comment]
"Window 7 On the SvgViewer window svg support is not available":
The problem here is that SvgViewer use all the 4 engines available to compare rendering, but D2DEngine is not supported on Windows 7. 

"On svgexplorer scale does not exist": simply remove from dfm
