### ISSUE TITLE
Wrong color on Android

### ISSUE THREAD

**Issue by kameisan** [EtheaDev/SVGIconImageList#260]
SVGIconImageList with Image32 on Android displays svg image well, but wrong color .
( I know it not support Android currently, but ... )

**Comment by carloBarazzetta** [comment]
Oh no...
Here a very long discussion on this problem: 
https://github.com/EtheaDev/SVGIconImageList/issues/229
I've no control over Image32 rendering on Android: yesterday I've aligned my Image32 source code to the same source code of Angus, so I don't know how to fix this problem: are you using the lastet versione of my library?

**Comment by kameisan** [comment]
I downloaded v4.1.0 and rebuilt my app, but the problem did not improve.
so, I changed following line in FMX.Image32SVG.pas:
(before) LSource := TBitMapData.Create(FImage32.Width, FImage32.Height, TPixelFormat.BGRA);
(after) LSource := TBitMapData.Create(FImage32.Width, FImage32.Height, TPixelFormat.{$IF Defined(ANDROID)RGBA{$ELSE}BGRA{$ENDIF});
It's looks like the problem fixed.
