### ISSUE TITLE
Rotate does not work properly with renderer and viewbox

### ISSUE THREAD

**Issue by ase379** [EtheaDev/SVGIconImageList#261]
When I use the image attached, it looks fine in the web. But on a Canvas, the image is not rotates

Web:
![b](https://github.com/EtheaDev/SVGIconImageList/assets/34981282/567f4f8c-b0ae-4c56-b62e-844ce1f463ef)

Image
<img width="218" alt="image" src="https://github.com/EtheaDev/SVGIconImageList/assets/34981282/4027f3f4-5cf5-4450-874a-590dcc1b716b">
I debugged it an it seems, as if the viewport is not rotated. The same for the width and the height.
I now intercepted the width and height, but its quity hacky. I did not find a solution for the viewport now.
Can you fix this ?

**Comment by carloBarazzetta** [comment]
It's a question for [Angus Johnson](https://github.com/AngusJohnson), the author of Image32 engine.
