### ISSUE TITLE
href and clicking

### ISSUE THREAD

**Issue by bcp-software** [EtheaDev/SVGIconImageList#262]
I would love to find a way to detect mouseover and/or mouseclicks when a href is declared in the SVG content. I have a hard time figuring out where to start for this. Obviously some coordinate translation needs to happen, and some element iteration. But none of the elements are published in the ISVG, so opening the components to find an entrance is hard. Any ideas on this?

**Comment by carloBarazzetta** [comment]
Sorry but this component only render an SVG image on a "canvas"... to obtain scaled pictures for imagelist... The <href> feature is not available and out of scope for this component...
