### ISSUE TITLE
TSVGIconImageList doesn't load the icon colours for all icons

### ISSUE THREAD

**Issue by EricWex** [EtheaDev/SVGIconImageList#269]
![Block Change](https://github.com/EtheaDev/SVGIconImageList/assets/157601796/b9d9dd6f-1982-4c72-bcf7-07e6f7a8d073)
![Swap (1)](https://github.com/EtheaDev/SVGIconImageList/assets/157601796/7ca77b7e-071b-4908-9c8a-052b4ab46622)

The Style tag inside the error prone SVG files has a certain property named stroke-width: 0px. This property is always shared between a number of classes, e.g.:
Image

The position of this style is what causes the icons to misbehave. If I shift this style to be the last style in the file's Style tag, the colours render correctly: 

Image

Funny enough, the images display fine without any modifications in a browser, and in the File Explorer Preview Pane. 

Here are the code 
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <defs>
    <style>
      .cls-1 {
        fill: #999;
      }

      .cls-1, .cls-2, .cls-3, .cls-4 {
        stroke-width: 0px;
      }

      .cls-2 {
        fill: #0071bc;
      }

      .cls-3 {
        fill: #ccc;
      }

      .cls-4 {
        fill: #fff;
      }
    </style>
  </defs>
  <rect class="cls-3" x="3" y="10" width="22" height="4"/>
  <polygon class="cls-3" points="31 12 19 4 22.5 12 19 20 31 12"/>
  <rect class="cls-1" x="7" y="21" width="22" height="4" transform="translate(36 46) rotate(180)"/>
  <polygon class="cls-1" points="1 23 13 31 9.5 23 13 15 1 23"/>
  <g>
    <path class="cls-2" d="m9,1C4.58,1,1,4.58,1,9s3.58,8,8,8,8-3.58,8-8S13.42,1,9,1Z"/>
    <path class="cls-4" d="m4.61,14.38c-.08-.08-.11-.17-.11-.27V3.89c0-.12.04-.21.11-.28.08-.07.16-.11.27-.11h4.63c1.28,0,2.22.27,2.85.81s.93,1.31.93,2.3c0,.52-.13.97-.39,1.33-.26.36-.55.63-.87.79.42.2.76.52,1.05.96.28.44.42.93.42,1.48,0,1.05-.33,1.87-1,2.45-.67.59-1.62.88-2.85.88h-4.77c-.1,0-.19-.04-.27-.12Zm4.59-6.51c.4,0,.71-.11.93-.32.21-.21.32-.5.32-.86s-.11-.62-.32-.83c-.21-.21-.52-.31-.93-.31h-1.97v2.33h1.97Zm.14,4.59c.42,0,.74-.13.97-.38.23-.25.35-.55.35-.91,0-.38-.12-.69-.35-.93-.23-.25-.56-.37-.97-.37h-2.11v2.59h2.11Z"/>
  </g>
</svg>

and this is our fix
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <defs>
    <style>
      .cls-1 {
        fill: #999;
      }

      .cls-2 {
        fill: #0071bc;
      }

      .cls-3 {
        fill: #ccc;
      }

      .cls-4 {
        fill: #fff;
      }
    </style>
  </defs>
  <rect class="cls-3" x="3" y="10" width="22" height="4"/>
  <polygon class="cls-3" points="31 12 19 4 22.5 12 19 20 31 12"/>
  <rect class="cls-1" x="7" y="21" width="22" height="4" transform="translate(36 46) rotate(180)"/>
  <polygon class="cls-1" points="1 23 13 31 9.5 23 13 15 1 23"/>
  <g>
    <path class="cls-2" d="m9,1C4.58,1,1,4.58,1,9s3.58,8,8,8,8-3.58,8-8S13.42,1,9,1Z"/>
    <path class="cls-4" d="m4.61,14.38c-.08-.08-.11-.17-.11-.27V3.89c0-.12.04-.21.11-.28.08-.07.16-.11.27-.11h4.63c1.28,0,2.22.27,2.85.81s.93,1.31.93,2.3c0,.52-.13.97-.39,1.33-.26.36-.55.63-.87.79.42.2.76.52,1.05.96.28.44.42.93.42,1.48,0,1.05-.33,1.87-1,2.45-.67.59-1.62.88-2.85.88h-4.77c-.1,0-.19-.04-.27-.12Zm4.59-6.51c.4,0,.71-.11.93-.32.21-.21.32-.5.32-.86s-.11-.62-.32-.83c-.21-.21-.52-.31-.93-.31h-1.97v2.33h1.97Zm.14,4.59c.42,0,.74-.13.97-.38.23-.25.35-.55.35-.91,0-.38-.12-.69-.35-.93-.23-.25-.56-.37-.97-.37h-2.11v2.59h2.11Z"/>
  </g>
      .cls-1, .cls-2, .cls-3, .cls-4 {
        stroke-width: 0px;
      }

</svg>

**Comment by carloBarazzetta** [comment]
Are you using Image32 Engine?

**Comment by carloBarazzetta** [comment]
it's a problems inside the Image32 engine... You must open the issue in the https://github.com/AngusJohnson/Image32 repo.
When Angus Johnson resolve the problem you can replace your units into Image32\Source units of this project.
