### ISSUE TITLE
Using TSVGIconImage on Delphi 12 doesn't make MacOS 64 build

### ISSUE THREAD

**Issue by gdacunto** [EtheaDev/SVGIconImageList#270]
Hi! 
Delphi 12 - FMX - TSvgIconImage
We noticed that simply inserting a tsvgiconimage into an empty Delphi 12 FMX project, using the default engine, builds for Windows but not for Mac.
This happens when using version 4.1.2 but not with 3.9.6
The strange thing, which also happens on Windows, seems to be related to the FireMonkeyVersion define which is not read correctly and causes the Mac build to fail when the Img32 unit (Angus Johnson) tries to include Vcl.* units instead of FMX units as expected.

**Comment by gdacunto** [comment]
This issue will be solved when a new release of the Angus Johnson engine will be released and updated in this project.
https://github.com/AngusJohnson/Image32/issues/46

**Comment by carloBarazzetta** [comment]
Ok, thanks.

**Comment by gdacunto** [comment]
Hi!
 would let you know that Angus Johnson committed the fix that solve this issue.
https://github.com/AngusJohnson/Image32/commit/614a7d759d9151c1b9e25607a28fb5f652eaf444

**Comment by carloBarazzetta** [comment]
Fixed also here...
