### ISSUE TITLE
4.1.3 + VCL + Image32SVGFactory + colors

### ISSUE THREAD

**Issue by kazuser** [EtheaDev/SVGIconImageList#273]
I don't understand 🥲

`<svg width="128" height="128" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill="#fff" d="M0 0h128v128H0z"/></svg>`
= 255, 255, 255

`<svg width="2" height="2" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0 .5h2M.5 0v2" stroke="#fff"/></svg>`
= 254, 254, 254

![0](https://github.com/EtheaDev/SVGIconImageList/assets/3335273/d1343993-1394-4f27-b8a0-8f114d75ee0d)

[Project1.zip](https://github.com/EtheaDev/SVGIconImageList/files/15139038/Project1.zip)

**Comment by carloBarazzetta** [comment]
You must ask to Angus Johnson, author of Image32 library, for "rendering problems"...
https://github.com/AngusJohnson/Image32
