### ISSUE TITLE
TSVGIconImageListBase.Assign misses ApplyFixedColorToRootOnly property

### ISSUE THREAD

**Issue by pyscripter** [EtheaDev/SVGIconImageList#275]
Please add to TSVGIconImageListBase.Assign

`FApplyFixedColorToRootOnly := TSVGIconImageListBase(Source).FApplyFixedColorToRootOnly;`

An implication is that the ApplyFixedColorToRootOnly property is reset every time you edit an SVGIconImageList.

**Comment by carloBarazzetta** [comment]
Fixed in 4.1.5 version
