### ISSUE TITLE
Skia units have been renamed in v6.0.0

### ISSUE THREAD

**Issue by DeveloppeurPascal** [EtheaDev/SVGIconImageList#277]
Hi
Skia units have been renamed since its integration in Delphi 12 Athens.
Do you allow me to create a PULL REQUEST to fix them on the library ?
@+
Patrick

**Comment by carloBarazzetta** [comment]
Hello Patrick. I can use Skia from SvgIconImageList without problems: in which unit do you find the incorrect name? It was fixed in 4.1.1 version...

**Comment by carloBarazzetta** [comment]
Fixed in 4.1.7 version ;-)

**Comment by DeveloppeurPascal** [comment]
Thanks ;)
