### ISSUE TITLE
TSVGIconImageCollection goes missing...

### ISSUE THREAD

**Issue by ijbranch** [EtheaDev/SVGIconImageList#278]
Win 11, D12.1, 32bit apps.  Using Image32 option.
If I install SVGIconsImageList from GitHub it builds and installs OK, and initially is fine.
When I go to use it the next day, it seems to have lost TSVGIconImageCollection.  Or more precisely, Delphi says it can't find it at design time.
If I install via GetIt, all is fine.

This is repeatable.

Thoughts/suggestions?
Ian

**Comment by carloBarazzetta** [comment]
I have no idea, I'll investigate the problem and update the project as soon as possible...

**Comment by ijbranch** [comment]
Hi Carlo.  Any progress?

**Comment by carloBarazzetta** [comment]
No, I'm releasing a new version in a few days and request to Emb to update the GetIt version.
The only reason for the component "disappear" from the IDE, is that the package installed is not available: after starting IDE, open Components/Install Packages and check if "Ethea SVGIconImageList VCL components" is "checked".

**Comment by ijbranch** [comment]
Hi Carlo,
              I have deinstalled the GetIt version and reinstalled the GitHub version.
              I rebooted my PC and all is good att.
              It normally manifests itself some time the next day so I will get back to you.

Regards,
Ian
The Programmer's Credo:  We do these things not because they are easy, but because we thought they were going to be easy... ***@***.*** - 05/08/2016)
