### ISSUE TITLE
Error when rename an icon

### ISSUE THREAD

**Issue by marchomal** [EtheaDev/SVGIconImageList#279]
Hi,
After rename an icon the ide show incorrect others icons
![beforerename](https://github.com/user-attachments/assets/3c4f95ac-d648-4c6a-850c-a49f6047bac4)

After rename de icon 32.jpg as 32.jpg-- the icon 32.html is not shown
![afterrename](https://github.com/user-attachments/assets/d1720f31-9b92-4cd9-b539-7a65c111ef50)

![afterrename](https://github.com/user-attachments/assets/3e000ccc-34f5-4c13-a38f-791c1aec0d7d)
![beforerename](https://github.com/user-attachments/assets/6c2f0288-31bc-4686-975b-07c7ee834e0e)

**Comment by carloBarazzetta** [comment]
Fixed in 4.1.9 version
