### ISSUE TITLE
Rendering issue strokes

### ISSUE THREAD

**Issue by BvdLind** [EtheaDev/SVGIconImageList#281]
It seems that after version 4.1.5 strokes aren't drawn properly anymore. 

In version 4.1.5 it's perfect like in this example: 
<img width="1298" alt="Screenshot 2024-10-16 at 11 05 23" src="https://github.com/user-attachments/assets/c1ff9941-6c22-4675-b159-5669cfd89eb5">

But the same code in later versions gives this:
<img width="1059" alt="Screenshot 2024-10-16 at 11 03 02" src="https://github.com/user-attachments/assets/a14fe2ad-f657-46f2-9045-23fd98f4ca55">

So something in this commit https://github.com/EtheaDev/SVGIconImageList/commit/b366d5fc379e69ffca366aca03b7ae3f71581dfe seems to have broken it.

**Comment by carloBarazzetta** [comment]
Fixed in 4.2.1 version
