### ISSUE TITLE
cases where SVG icons do not scale with the Windows scaling factor

### ISSUE THREAD

**Issue by georges-hatem** [EtheaDev/SVGIconImageList#284]
Hello,
Browsing the issues, I found a few related to scaling, though I'm not sure if they overlap with this one.
 - link an SVGvirtualImageList to a TMainMenu, the icons do not scale when launched at a higher scaling factor
 - link an SVGvirtualImageList to a programmatically created TSpeedButton, similar scaling issue

Note that, when done at design-time, the button size scales, and the SVG image scales with it, without any manual intervention.

Here is a screenshot of the MenuItem with the small glyph at scaling factor 150%.
Note that, in both cases, manually tweaking the SvgVirtualImageList.Size does impact the icons.

The question is, should it be done manually on program start?
Is there a better way to achieve the expected scaling result?

Thanks

![image](https://github.com/user-attachments/assets/6d5cb0f7-dfb5-481e-9aa4-50d8c9bd2554)

**Comment by pyscripter** [comment]
SVGvirtualImageList  is for old Delphi versions.  Use a standard VirutalImageList, linked to an SVGImageCollection instead.

**Comment by georges-hatem** [comment]
Got it thanks. 
However, the external behavior seems to be the same: scaling isn't done automatically, I have to manually multiply width and height by 1.5 (150% scaling).

Any ideas?

**Comment by pyscripter** [comment]
> Got it thanks. However, the external behavior seems to be the same: scaling isn't done automatically, I have to manually multiply width and height by 1.5 (150% scaling).

You must be doing something wrong.   Read the documentation about the VirtualImageList.   The whole point is that DPI scaling is done automatically

**Comment by carloBarazzetta** [comment]
I'll investigate as soon as possible...

**Comment by carloBarazzetta** [comment]
Can you give me a zip with a sample example to check the problem?

**Comment by georges-hatem** [comment]
[SVG-imagelist.zip](https://github.com/user-attachments/files/17732396/SVG-imagelist.zip)

Apologies for the delay, got side-tracked.
Easy steps to reproduce: put the SVG image collection and VirtualImageList in a data-module, and not on a form.  Attached is a sample.

If I'm not mistaken, data-modules being non-visual will not take scaling into consideration.
But I don't know if this is a Delphi thing or related to SVGIconImageList.

**Comment by carloBarazzetta** [comment]
Your zip contains many mistakes:
1) the datamodule is not added to the project so it's not created at runtime
2) the virtualimagelist "must" be placed on the Form, not into the Datamodule
3) connecting the VirtualImageList to the ImageCollection of the datamodule and the MainManu to the VirtualImageList, running the App the icon appears in correct size, as in this image, with a 150% dpi monitor:
![image](https://github.com/user-attachments/assets/57cb31bb-c75e-4b90-b224-e75d9ba428ea)
