### ISSUE TITLE
change $IFEND to $ENDIF

### ISSUE THREAD

**Issue by birbilis** [EtheaDev/SVGIconImageList#285]
at
https://github.com/EtheaDev/SVGIconImageList/blob/0dfb25b723f01639473086de11abf74d987bdeec/Source/FMX.Image32SVG.pas#L178
there's an $IFEND instead of $ENDIF causing Delphi compiler to emit hint

[dcc32 Hint] FMX.Image32SVG.pas(178): H2586 Legacy '$IFEND' directive found. Consider changing to '$ENDIF' or enable $LEGACYIFEND

if for some reason you need $IFEND for older Delphis (though later on below in same unit there's an $ENDIF being used, can add $LEGACYIFEND to have the compiler not complain about it

**Comment by carloBarazzetta** [comment]
Fixed in 4.3.0
