### ISSUE TITLE
Error installing Desgin Packaging dclsvgiconImageList280 in delphi 11.2

### ISSUE THREAD

**Issue by MAUROFAILO** [EtheaDev/SVGIconImageList#287]
On installing design Packaging of dclsvgiconImageList280, show this message:
![image](https://github.com/user-attachments/assets/110e432c-1cc4-4b47-b3a3-3fc9607a7a84)

**Comment by carloBarazzetta** [comment]
Try to exit IDE, load package group, uninstall, rebuild, and reinstall design package.
