### ISSUE TITLE
Icon Editor not keeping added icons

### ISSUE THREAD

**Issue by GNiessen** [EtheaDev/SVGIconImageList#3]
After building and installing the SVGIconImageList, I added the two components to a project.  Then I tried to Add a new Icon.  I browsed to the file and it looked like it added, as I saw the preview and could adjust the size.  Clicking OK closed the window.  And I tried to set a SVGIconImage component to that index "0".  But nothing showed.  And when I re-opened the editor, the image is gone.

I also tried opening the SVGIconItems and manually adding it.  But I could add the new item, I was unable to paste the text in the SVGText box.  It appears to only allow a very minimal amount of text and the was no way to bring up a larger window to enter or edit the text.

I even tried to add several of the sample Icons and was unsuccessful.

**Comment by carloBarazzetta** [comment]
I'll fix this problem in the next release, tomorrow...

**Comment by carloBarazzetta** [comment]
Resolved in 1.2 version.

**Comment by GNiessen** [comment]
It is working now.  Thank you.
