### ISSUE TITLE
FixedColor and memory leak

### ISSUE THREAD

**Issue by TextEditorPro** [EtheaDev/SVGIconImageList#39]
Neither FixedColor property nor icon fixed color does work in the latest version 1.8.0. Also if you change the icon fixed color there is a memory leak: "An unexpected memory leak has occured. The unexpected small block leaks are: 21-28 bytes: AnsiString x 1".

The color was working in previous version. The memory leak was already there.

**Comment by carloBarazzetta** [comment]
@pyscripter is working to change FixedColor property to a native Delphi TColor. I suppose in the next release the problem will fixed.

**Comment by pyscripter** [comment]
The latest PR #40 fixes that.

**Comment by carloBarazzetta** [comment]
With the last push I merged the great work of @pyscripter in the main branch. FixedColor was changed from TSVGColor (a limited set of colors) to a native Delphi TColor.
Now, changing global FixedColor in the component editor works fine, but changing a fixed color of a single element does not, but if the changes is made into object-inspector works fine, so I suppose it's only an editor's bug.
But now I think that the two FixedColor combo-boxes in the component editor must be replaced with a standard TColorBox component. Do you agree?

**Comment by TextEditorPro** [comment]
I agree, if you ask me. The component editor also colored the icon before. It is easier to see which icons are colored.

**Comment by TextEditorPro** [comment]
Also there should be a custom color.

**Comment by carloBarazzetta** [comment]
Fixed in 1.9 version and changed component editor with TColorBox
