### ISSUE TITLE
Demo application doesn't scale properly

### ISSUE THREAD

**Issue by xraymike** [EtheaDev/SVGIconImageList#4]
Thank you for writing this component; it looks like an interesting and useful component!

There's a problem, though...the Demo application doesn't scale properly.  The TListView and TTreeView loses all its images when moved to a screen that uses a higher DPI (in my case, this high DPI monitor is 192 DPI).

I'm using it with Delphi 10.3 and HiDPISupport is defined.

I found that after a DPI change, it was necessary to call TSVGIconImageList.RecreateBitmaps( ) otherwise the images would be blank.  I'd expect TSVGIconImageList.DPIChangedMessageHandler( ) should probably call the RecreateBitmaps( ) method after the size change has been completed.

**Comment by carloBarazzetta** [comment]
Yes! Call RecreateBitmaps; after StopDrawing(False) into .DPIChangedMessageHandler.
Thank you.

**Comment by carloBarazzetta** [comment]
Fixed in 1.3 release.
