### ISSUE TITLE
FixedColor is not working

### ISSUE THREAD

**Issue by TextEditorPro** [EtheaDev/SVGIconImageList#50]
FixedColor does not work. Images are always black. Even if you set both FixedColors to white. 

![image](https://user-images.githubusercontent.com/69666569/90804519-04ac9080-e323-11ea-830c-af600538fcf8.png)

Also the editor is not showing the color.

![image](https://user-images.githubusercontent.com/69666569/90804752-505f3a00-e323-11ea-8114-3422ffed6906.png)

**Comment by carloBarazzetta** [comment]
I've made some tests with the icons present in the demo and it works... 
Are you using a SVGVirtualImageList with a collection or a native VirtualImageList? 
Your Delphi version?

**Comment by TextEditorPro** [comment]
I was testing TSVGIconImageList component and my Delphi was communist version 10.3.3.

**Comment by TextEditorPro** [comment]
SVGs are from fontawesome.

**Comment by pyscripter** [comment]
> communist version

that explains the issue :)

**Comment by TextEditorPro** [comment]
I can test in version 10.4...

**Comment by carloBarazzetta** [comment]
It's very strange... try to use the demo app, clear all default icons and use "build from files..." button to load your icons and change Fixed Color... all the icons (except the ones on the toolbar) should be rendered in selected color...
Or send me some of your icons to test...

**Comment by TextEditorPro** [comment]
It is same with version 10.4. It seems to be a fontawesome issue. Try for example with this https://fontawesome.com/icons/ad?style=solid

**Comment by TextEditorPro** [comment]
I tested some other random svg I have and it looks strange but color works...

![image](https://user-images.githubusercontent.com/69666569/90865920-d1f2ae80-e39b-11ea-836b-602b92ca5c39.png)

**Comment by pyscripter** [comment]
> all the icons (except the ones on the toolbar)

For the toolbar icons to change as well you need to:
- Change the ImageList of the action list to VirtualImageList
- Add the following to TMainForm.GrayScaleCheckBoxClick
`
ImageDataModule.SVGIconImageCollection.GrayScale := GrayScaleCheckBox.Checked;
`

**Comment by pyscripter** [comment]
> It is same with version 10.4. It seems to be a fontawesome issue. Try for example with this https://fontawesome.com/icons/ad?style=solid

The problem is that these fontawesome svgs 
`svg
fill="currentColor"
`

This is for showing in a browser and taking the value of currentColor from the Web page style sheet.
Maybe TSVG should provide some handling of currentColor.

**Comment by pyscripter** [comment]
In SVGColor function GetSVGColor  add at the top below 'inherit' handling:
```pascal
  if SameText(ASVGColorName, 'currentColor') then
  begin
    Result := TColors.Black;
    Exit;
  end;
```

then it FixedColor works.

**Comment by TextEditorPro** [comment]
I updated the latest source and FixedColor does not work again.

**Comment by carloBarazzetta** [comment]
Try to change SVG engine setting {.$DEFINE PreferNativeSvgSupport} into SVGIconImageList.inc to return to TSVG implementation... (now the default Direct2D)

**Comment by carloBarazzetta** [comment]
Yes, I confirm the problem is present only using Direct2D...

**Comment by TextEditorPro** [comment]
So, FixedColor does not work by default?

**Comment by carloBarazzetta** [comment]
It seems to me that it has been fixed! 
Have you tried with the latest version?

**Comment by TextEditorPro** [comment]
I finally had time to test this. I tested the latest source and it works now. Little "bug" in editor that if you change the icon color the icon is not updated immediately.

Btw. There are some warnings and hints when building packages.

![image](https://user-images.githubusercontent.com/69666569/92017469-81e0f800-ed5c-11ea-9522-bfb83169121c.png)

**Comment by pyscripter** [comment]
LoadFromString will be removed in a forthcoming PR
Duplicate Resource:  Clean up your package folder before installing.
Class constructors:  Which version of Delphi are you using?

**Comment by vincentparrett** [comment]
The unsupported language feature suggests the package is outputting C++ Builder libs
