### ISSUE TITLE
SVGIconImageList.dpk is missing files

### ISSUE THREAD

**Issue by pyscripter** [EtheaDev/SVGIconImageList#62]
The four files added in my last PR are missing from the SVGIconImageList.dpk.

 ```pascal
 SVGInterfaces in '..\..\Source\SVGInterfaces.pas',
  D2DSVGHandler in '..\..\Source\D2DSVGHandler.pas',
  PasSVGHandler in '..\..\Source\PasSVGHandler.pas',
  Winapi.D2DMissing in '..\..\Source\Winapi.D2DMissing.pas';
```

**Comment by carloBarazzetta** [comment]
Sorry, I've lost them during realign of other packages.

**Comment by pyscripter** [comment]
Looks great by the way.  The combination of SVGIconImageCollection/VirtualImageList works very much like the standard ImageCollection/VirtualImageList one.  PreserveItems and everything else works as expected.

**Comment by pyscripter** [comment]
And by the way I have talked to Jim McKeeth about making the project available through GetIt.
