### ISSUE TITLE
Official 2.0 release candidate also for GetIt

### ISSUE THREAD

**Issue by carloBarazzetta** [EtheaDev/SVGIconImageList#66]
Jim McKeeth asks us to publish this library on GetIt.

We can use today to do the latest tests and verify the stability, then we can release the official 2.0 version.

I'm closing the issue #42, the discussion continues here...

@pyscripter can you write a little documentation to integrate wiki documentation on the use of SetGlobalSVGHandler?

thanks to all!

**Comment by carloBarazzetta** [comment]
FMX version still works, I haven't updated the component editor to support categories...

**Comment by pyscripter** [comment]
Here is the documentation of SVG factories.  You can integrated that into the project Wiki and provide a link from the project page.
[SVGFactories.zip](https://github.com/EtheaDev/SVGIconImageList/files/5124666/SVGFactories.zip)

**Comment by carloBarazzetta** [comment]
> Here is the documentation of SVG factories. You can integrated that into the project Wiki and provide a link from the project page.
> [SVGFactories.zip](https://github.com/EtheaDev/SVGIconImageList/files/5124666/SVGFactories.zip)

Documentation integrated here: https://github.com/EtheaDev/SVGIconImageList/wiki/Choise-of-Factories-(Direct-2D-or-GDI-)
linked from readme and home of the wiki.

I updated the readme to list all the the features of 2.0: check if I missed something...

**Comment by pyscripter** [comment]
In the Wiki Home Page in the comparison between TVirtualImageList and TSVGIconVirtualImageList you should mention the following:

- TVirtualImageList and TSVGIconVirtualImageList both use images from TSVGIconImageCollection.  An important difference is that TVirtualImageList may use and create only a subset of the images in the collection, whereas TSVGIconVirtualImageList creates all images of the collection everytime it is needed (e,g. DPI change).

- Although TVirtualImageList does not have the FixedColor, GrayScale and Opacity properties, these properties exist at the TSVGIconImageCollection and they would be reflected on the linked TVirtualImageList.

To my mind TSVGIconVirtualImageList is of use, only for versions of Delphi before 10.3 (except if you want to mix styles, which as discussed makes no sense).

**Comment by carloBarazzetta** [comment]
I agree on everything, but I want to preserve SVGIconImageList only for backward compatibility.
We may report that usage is "deprecated" and recommend the use of TSVGIconImageCollection+TSVGIconVirtualImageList.
On a future version we can drop this old component from packages.

**Comment by pyscripter** [comment]
Sure.

**Comment by carloBarazzetta** [comment]
I've updated the wiki home... if it's ok, tomorrow I will also update the readme and if there are no more urgent things to fix we could release version 2.0!
Thanks again for the big help!

**Comment by luebbe** [comment]
> Documentation integrated here: https://github.com/EtheaDev/SVGIconImageList/wiki/Choise-of-Factories-(Direct-2D-or-GDI-)
> linked from readme and home of the wiki.

You probably intended to call the page "**Choice** of Factories (Direct 2D or GDI )" ;)

**Comment by carloBarazzetta** [comment]
Page renamed! Thanks.

**Comment by carloBarazzetta** [comment]
Are we ready for official release?

**Comment by carloBarazzetta** [comment]
Official 2.0 release published!

**Comment by pyscripter** [comment]
I was too late with the fix to #78

**Comment by carloBarazzetta** [comment]
Integrated! Thanks!

**Comment by carloBarazzetta** [comment]
Today I created the official 2.0.1 (contains the latest fixes) - can we submit this version to GetIt now?

**Comment by pyscripter** [comment]
Pls go ahead.

**Comment by carloBarazzetta** [comment]
Submitted.
