### ISSUE TITLE
Wrong factors in SVGParse.GetFactor

### ISSUE THREAD

**Issue by pyscripter** [EtheaDev/SVGIconImageList#67]
See https://github.com/ekot1/DelphiSVG/issues/16

**Comment by pyscripter** [comment]
Please note that #65 is not fixed.

**Comment by pyscripter** [comment]
I will be looking into this and will write a Wiki page about the choice of GlobalSVGFactory

**Comment by carloBarazzetta** [comment]
> Please note that #65 is not fixed.

Sorry, now it's ok.
