### ISSUE TITLE
Editor not applying new images

### ISSUE THREAD

**Issue by brianhig** [EtheaDev/SVGIconImageList#7]
When I add a couple of images through the image editor by clicking on the Add button the Apply button remains greyed out. If I click on the Ok button the new images are not saved. As a work-around, if I replace one on the images or drag and drop it to  different place in the list of images the Apply button becomes clickable and changes are saved when I click on the Apply and Ok buttons

**Comment by carloBarazzetta** [comment]
Resolved with 1.6 version.
