### ISSUE TITLE
Wiki page on the choice of factories.

### ISSUE THREAD

**Issue by pyscripter** [EtheaDev/SVGIconImageList#74]
I did some benchmarking with the cowboy.svg and it appears that the difference in performance was mostly due to double-buffering.  With double-buffering i.e. not drawing directly on screen TSVG performance is on a par with D2D.  So I suggest you change the paragraph on Performance to:

> There is not much difference between the two and either of them should be adequate.

**Comment by carloBarazzetta** [comment]
I've added a simple performance measure into SVGExplorer (used in full-screen mode to draw many icons):
folder svg_examples (4 complex images): 46msec. with D2D vs 172msec. without D2D.
folder flat-color-icons (329 icons): 188msec. with D2D vs 250msec. without D2D.
material design icons (5366 icons): 4171msec. with D2D vs 4703msec. without D2D.
font awesome solid (997 icons): 546msec. with D2D vs 641msec. without D2D.
In general, D2D is always the best choice, expecially for large and complex images.

Why do you say there are no differences?

**Comment by pyscripter** [comment]
I did not do as extensive a test as you did.   You can keep as is.

D2D does double buffering.  If you implement double buffering in TSVGIconImage the peformance difference would be smaller.  You could instead inherit TSVGIconImage from TWinControl and publish the DoubleBuffering property.   But leave that for the next version.

**Comment by carloBarazzetta** [comment]
DoubleBuffering implemented for TSVGIconImage ;-)
The performances drawing "Cowboy" have improved visibly.
I've made default DoubleBuffering to True: it's correct?

**Comment by pyscripter** [comment]
Double buffering only helps with TSVG.  It actually slows down D2D a bit, because it is already doing Double buffering.  You could leave the default at False and add a note in the Performance section of the Wiki page.

I have a couple of performance improvements for TSVG but I will leave them for a future version:
- Replace TMatrix with TAfineMatrix (see TD2DMatrix3X2F in Winapi.D2D1)
- Change PaintItem to not iterate throught the children of TSVGPath

**Comment by pyscripter** [comment]
You can also expose the ParentDoubleBuffered property of TIConImage, but do check for backward compatibility.

**Comment by carloBarazzetta** [comment]
Mmmm.... I've made a test using D2D but i can see

**Comment by carloBarazzetta** [comment]
In any cases, I decided to add DoubleBuffered and ParentDoubleBuffered as default...
