### ISSUE TITLE
SVG Explorer cannot paint all "NewSydneyVector" icons

### ISSUE THREAD

**Issue by luebbe** [EtheaDev/SVGIconImageList#76]
Compiled with todays version of SvgIconImageList. See Screenshot:

![image](https://user-images.githubusercontent.com/3872576/91283580-0d6dee00-e78b-11ea-9720-8dd0a0aa24c4.png)

**Comment by carloBarazzetta** [comment]
It's a problem with new Direct2D Support: change this line of code into SVGIconImageList.inc to disable:
{.$DEFINE PreferNativeSvgSupport}

**Comment by pyscripter** [comment]
From I can see, Direct2D does not support style sheets and the class attribute.  See https://docs.microsoft.com/en-us/windows/win32/direct2d/svg-support.

I think this should be mentioned in the Wiki page regarding choice of Factories.

**Comment by carloBarazzetta** [comment]
Wiki updated!

**Comment by carloBarazzetta** [comment]
@pyscripter: if we know the limit of Direct2D support (text, style, class), if the image contains an element that cannot be drawn with Direct2D, we can use TSWG: do you think it's possible?

**Comment by pyscripter** [comment]
In theory everything is possible, but I don't think is easy or worth the trouble.

**Comment by carloBarazzetta** [comment]
Closing issue, because those icons can be rendered using TSVG engine.
