### ISSUE TITLE
{$IFDEF D10_3+}Vcl.VirtualImageList,{$ENDIF} in forms

### ISSUE THREAD

**Issue by pyscripter** [EtheaDev/SVGIconImageList#79]
Having {$IFDEF D10_3+}Vcl.VirtualImageList,{$ENDIF} in Forms (Demo) is problematic, since Delphi is still trying to add its own and then complains about duplicate uses statement.

Not sure what the best solution is.

**Comment by carloBarazzetta** [comment]
I know... We can leave the uses without IFDEF and a comment for who compiles with older versions to remove it...

**Comment by carloBarazzetta** [comment]
Done!
