### ISSUE TITLE
Render Bug

### ISSUE THREAD

**Issue by ange007** [EtheaDev/SVGIconImageList#8]
Hello.
When switching icons quickly, they overlap each other.

![DP13m6VCRE](https://user-images.githubusercontent.com/2736539/86530931-bdc72080-bec5-11ea-87e6-a2032938b270.gif)

===

But this is not all, the same overlay occurs immediately upon application initialization (in my FMX application) on some icons.

![image](https://user-images.githubusercontent.com/2736539/86531001-552c7380-bec6-11ea-98dc-8207553e6532.png)
(compiled app)

![image](https://user-images.githubusercontent.com/2736539/86531029-92910100-bec6-11ea-8574-57d1e1cf94d5.png)
(app in IDE)

![aA9NUATBny](https://user-images.githubusercontent.com/2736539/86531049-b6544700-bec6-11ea-90ef-c899d5433748.gif)

This icons from: https://icons8.com/line-awesome _(tasks, users, list, cog)_

D10.3. Windows 10

**Comment by carloBarazzetta** [comment]
Fixed by pull-request.
