### ISSUE TITLE
LoadFromString is unnecessary and wrong

### ISSUE THREAD

**Issue by pyscripter** [EtheaDev/SVGIconImageList#94]
In #93 the LoadFromString method was added to the D2D and Pas factories.  This was unnecessary and wrong.

The proper way of loading from a string is to use the Source property of ISVG.  This also sets the FSource field of the underlying D2D implementation.

Please remove LoadFromString.

**Comment by vincentparrett** [comment]
I'll remove them since only the collection really needs them.. but I'm curious how that is different from LoadFromStream etc... LoadFromString calls LoadFromStream.

**Comment by pyscripter** [comment]
It doesn't set the encoding to UTF8 which is assumed by LoadFromStream.

**Comment by pyscripter** [comment]
Don't bother removing them.  I will do it since I want to merge some changes and there is a merge conflict.

**Comment by vincentparrett** [comment]
I already pushed a PR.  I can close it.. but still want to keep the LoadFromString on the collection.
