### ISSUE TITLE
Packages not up to date

### ISSUE THREAD

**Issue by luebbe** [EtheaDev/SVGIconImageList#98]
You are amazing, I'm still trying to catch up and find out the best way to use this component with my app.

Compiling todays sources I noticed that:
- svgproperties.pas should be removed from the packages
- Xmllite is explicitely imported
- PasSvgFactory.pas private "LoadFromString" is declared but never used

**Comment by carloBarazzetta** [comment]
Yes, I'm working on this.

**Comment by carloBarazzetta** [comment]
Done!
